// Ported from ufbx extra/ufbx_math.c (LIBM-based), v0.23.1
//
// Based on LIBM (https://www.netlib.org/libm/), originally:
//   Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
//   Developed at SunSoft, a Sun Microsystems, Inc. business.
//   Permission to use, copy, modify, and distribute this software is freely
//   granted, provided that this notice is preserved.
//
// This is a faithful, bit-exact C# port of extra/ufbx_math.c from ufbx
// v0.23.1. All integer bit manipulation mirrors the C code's
// uint32_t/int32_t semantics via unchecked contexts; double<->bits access
// uses BitConverter.DoubleToInt64Bits / Int64BitsToDouble, which carry the
// same 64 raw bits as the C union (ufbxm_double_bits / ufbxm_bits) access.
//
// Notes on the SSE/NEON macro paths in the C source (ufbx_math.c:26-48):
//  - ufbxm_sqrt(x) is the SSE2 sqrtsd instruction, which is IEEE-754
//    correctly rounded. System.Math.Sqrt lowers to the same instruction on
//    x64/arm64 and is bit-identical, including NaN payload handling, so it
//    is used for Sqrt. This is the ONLY System.Math use in this file;
//    everything else is a software port. (Verified against the `sqrt` rows
//    of tools/math_vectors.txt.)
//  - ufbxm_fabs(x) is `andnot` with -0.0 == clear the sign bit; implemented
//    with a bit mask in Abs().
//
// IMPORTANT: evaluation order and grouping must stay exactly as in the C
// source; do not reorder operands or fold terms. FP semantics: the golden
// reference build uses NO FP contraction (zig cc -O2 -mcpu=x86_64
// -ffp-contract=off), so every C `x*y + z` double-rounds and the C# port
// writes the same plain arithmetic. The multiply-feeding-add sites in the
// LIBM kernels are marked UfbxMath.Fma(x, y, z) (see UfbxFma.cs), which now
// reduces to `a*b + c` — the name documents "this product feeds an add in
// the C source" and is where a contraction-enabled build would differ.
// Verified: 72000/72000 on tools/math_vectors.txt (generated by the same
// no-contraction build). See PORTING_NOTES.md「浮点语义」.

using System;

namespace Ufbx
{
    internal static partial class UfbxMath
    {
        // ------------------------------------------------------------------
        // -- double/bits conversion (ufbxm_to_bits / ufbxm_from_bits / ...)
        //    ufbx_math.c:99-135. Little-endian layout: hi = high 32 bits.
        // ------------------------------------------------------------------

        private static ulong ToBits(double x)
        {
            return unchecked((ulong)BitConverter.DoubleToInt64Bits(x));
        }

        private static double FromBits(ulong bits)
        {
            return BitConverter.Int64BitsToDouble(unchecked((long)bits));
        }

        // ufbxm_hi: high 32-bit word of the double, as int
        private static int Hi(double x)
        {
            return unchecked((int)(uint)(ToBits(x) >> 32));
        }

        // low 32-bit word of the double, as uint
        private static uint Lo(double x)
        {
            return unchecked((uint)ToBits(x));
        }

        // ufbxm_from_bits
        private static double FromHiLo(int hi, uint lo)
        {
            return FromBits(((ulong)(uint)hi << 32) | lo);
        }

        // ufbxm_zero_lo
        private static double ZeroLo(double x)
        {
            return FromHiLo(Hi(x), 0u);
        }

        // ufbxm_set_hi
        private static double SetHi(double x, int hi)
        {
            return FromHiLo(hi, Lo(x));
        }

        // ------------------------------------------------------------------
        // ufbx_copysign, ufbx_math.c:150-155
        // ------------------------------------------------------------------

        public static double CopySign(double x, double y)
        {
            unchecked
            {
                int xh = Hi(x);
                int yh = Hi(y);
                return FromHiLo((xh & 0x7fffffff) | (yh & unchecked((int)0x80000000u)), Lo(x));
            }
        }

        // ------------------------------------------------------------------
        // ufbx_fabs, ufbx_math.c:157-165 (SSE path: andnot with -0.0)
        // ------------------------------------------------------------------

        public static double Abs(double x)
        {
            return FromBits(ToBits(x) & 0x7fffffffffffffffUL);
        }

        // ------------------------------------------------------------------
        // ufbx_scalbn, ufbx_math.c:167-211
        // ------------------------------------------------------------------

        internal static double Scalbn(double x, int n)
        {
            const double two54 = 1.80143985094819840000e+16;  /* 0x43500000, 0x00000000 */
            const double twom54 = 5.55111512312578270212e-17; /* 0x3C900000, 0x00000000 */
            const double huge = 1.0e+300;
            const double tiny = 1.0e-300;

            unchecked
            {
                int k, hx;
                uint lx;
                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32));
                lx = (uint)bx;
                k = (hx & 0x7ff00000) >> 20; /* extract exponent */
                if (k == 0)
                { /* 0 or subnormal x */
                    if ((lx | (uint)(hx & 0x7fffffff)) == 0)
                        return x; /* +-0 */
                    x *= two54;
                    bx = ToBits(x);
                    hx = unchecked((int)(uint)(bx >> 32));
                    k = ((hx & 0x7ff00000) >> 20) - 54;
                    if (n < -50000)
                        return tiny * x; /* underflow */
                }
                if (k == 0x7ff)
                    return x + x; /* NaN or Inf */
                k = k + n;
                if (k > 0x7fe)
                    return huge * CopySign(huge, x); /* overflow */
                if (k > 0) /* normal result */
                {
                    hx = (hx & unchecked((int)0x800fffffu)) | (k << 20);
                    return FromHiLo(hx, (uint)bx);
                }
                if (k <= -54)
                {
                    if (n > 50000) /* in case integer overflow in n+k */
                        return huge * CopySign(huge, x); /* overflow */
                    else
                        return tiny * CopySign(tiny, x); /* underflow */
                }
                k += 54; /* subnormal result */
                hx = (hx & unchecked((int)0x800fffffu)) | (k << 20);
                return FromHiLo(hx, (uint)bx) * twom54;
            }
        }

        // ------------------------------------------------------------------
        // ufbx_floor, ufbx_math.c:213-284
        // ------------------------------------------------------------------

        public static double Floor(double x)
        {
            const double huge = 1.0e300;

            unchecked
            {
                int i0, i1, j0;
                uint i, j;
                ulong xb = ToBits(x);
                i0 = unchecked((int)(uint)(xb >> 32));
                i1 = unchecked((int)(uint)xb);
                j0 = ((i0 >> 20) & 0x7ff) - 0x3ff;
                if (j0 < 20)
                {
                    if (j0 < 0)
                    { /* raise inexact if x != 0 */
                        if (huge + x > 0.0)
                        { /* return 0*sign(x) if |x|<1 */
                            if (i0 >= 0)
                            {
                                i1 = 0;
                                i0 = 0;
                            }
                            else if (((i0 & 0x7fffffff) | i1) != 0)
                            {
                                i0 = unchecked((int)0xbff00000u);
                                i1 = 0;
                            }
                        }
                    }
                    else
                    {
                        i = 0x000fffffu >> j0;
                        if (((i0 & unchecked((int)i)) | i1) == 0)
                            return x; /* x is integral */
                        if (huge + x > 0.0)
                        { /* raise inexact flag */
                            if (i0 < 0)
                                i0 += 0x00100000 >> j0;
                            i0 &= unchecked((int)~i);
                            i1 = 0;
                        }
                    }
                }
                else if (j0 > 51)
                {
                    if (j0 == 0x400)
                        return x + x; /* inf or NaN */
                    else
                        return x; /* x is integral */
                }
                else
                {
                    i = 0xffffffffu >> (j0 - 20);
                    if ((i1 & unchecked((int)i)) == 0)
                        return x; /* x is integral */
                    if (huge + x > 0.0)
                    { /* raise inexact flag */
                        if (i0 < 0)
                        {
                            if (j0 == 20)
                                i0 += 1;
                            else
                            {
                                j = (uint)i1 + (1u << (52 - j0));
                                if (j < (uint)i1)
                                    i0 += 1; /* got a carry */
                                i1 = unchecked((int)j);
                            }
                        }
                        i1 &= unchecked((int)~i);
                    }
                }
                return FromHiLo(i0, (uint)i1);
            }
        }

        // ------------------------------------------------------------------
        // ufbx_frexp, ufbx_math.c:286-310 (kept for completeness; unused here)
        // ------------------------------------------------------------------

        internal static double Frexp(double x, out int e)
        {
            const double two54 = 1.80143985094819840000e+16; /* 0x43500000, 0x00000000 */

            unchecked
            {
                int hx, ix;
                uint lx;
                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32));
                lx = (uint)bx;
                ix = 0x7fffffff & hx;
                e = 0;
                if (ix >= 0x7ff00000 || ((ix | unchecked((int)lx)) == 0))
                    return x; /* 0,inf,nan */
                if (ix < 0x00100000)
                { /* subnormal */
                    x *= two54;
                    bx = ToBits(x);
                    hx = unchecked((int)(uint)(bx >> 32));
                    ix = hx & 0x7fffffff;
                    e = -54;
                }
                e += (ix >> 20) - 1022;
                hx = (hx & unchecked((int)0x800fffffu)) | 0x3fe00000;
                return FromHiLo(hx, (uint)bx);
            }
        }

        // ------------------------------------------------------------------
        // ufbx_atan, ufbx_math.c:312-414
        // ------------------------------------------------------------------

        private static readonly double[] AtanHi =
        {
            4.63647609000806093515e-01, /* atan(0.5)hi 0x3FDDAC67, 0x0561BB4F */
            7.85398163397448278999e-01, /* atan(1.0)hi 0x3FE921FB, 0x54442D18 */
            9.82793723247329054082e-01, /* atan(1.5)hi 0x3FEF730B, 0xD281F69B */
            1.57079632679489655800e+00, /* atan(inf)hi 0x3FF921FB, 0x54442D18 */
        };

        private static readonly double[] AtanLo =
        {
            2.26987774529616870924e-17, /* atan(0.5)lo 0x3C7A2B7F, 0x222F65E2 */
            3.06161699786838301793e-17, /* atan(1.0)lo 0x3C81A626, 0x33145C07 */
            1.39033110312309984516e-17, /* atan(1.5)lo 0x3C700788, 0x7AF0CBBD */
            6.12323399573676603587e-17, /* atan(inf)lo 0x3C91A626, 0x33145C07 */
        };

        private static readonly double[] AtanT =
        {
            3.33333333333329318027e-01,	 /* 0x3FD55555, 0x5555550D */
            -1.99999999998764832476e-01, /* 0xBFC99999, 0x9998EBC4 */
            1.42857142725034663711e-01,	 /* 0x3FC24924, 0x920083FF */
            -1.11111104054623557880e-01, /* 0xBFBC71C6, 0xFE231671 */
            9.09088713343650656196e-02,	 /* 0x3FB745CD, 0xC54C206E */
            -7.69187620504482999495e-02, /* 0xBFB3B0F2, 0xAF749A6D */
            6.66107313738753120669e-02,	 /* 0x3FB10D66, 0xA0D03D51 */
            -5.83357013379057348645e-02, /* 0xBFADDE2D, 0x52DEFD9A */
            4.97687799461593236017e-02,	 /* 0x3FA97B4B, 0x24760DEB */
            -3.65315727442169155270e-02, /* 0xBFA2B444, 0x2C6A6C2F */
            1.62858201153657823623e-02,	 /* 0x3F90AD3A, 0xE322DA11 */
        };

        public static double Atan(double x)
        {
            const double one = 1.0;
            const double huge = 1.0e300;

            unchecked
            {
                double w, s1, s2, z;
                int ix, hx, id;

                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32));
                ix = hx & 0x7fffffff;
                if (ix >= 0x44100000)
                { /* if |x| >= 2^66 */
                    if (ix > 0x7ff00000 ||
                        (ix == 0x7ff00000 && (uint)bx != 0))
                        return x + x; /* NaN */
                    if (hx > 0)
                        return AtanHi[3] + AtanLo[3];
                    else
                        return -AtanHi[3] - AtanLo[3];
                }
                if (ix < 0x3fdc0000)
                { /* |x| < 0.4375 */
                    if (ix < 0x3e200000)
                    { /* |x| < 2^-29 */
                        if (huge + x > one)
                            return x; /* raise inexact */
                    }
                    id = -1;
                }
                else
                {
                    x = Abs(x);
                    if (ix < 0x3ff30000)
                    { /* |x| < 1.1875 */
                        if (ix < 0x3fe60000)
                        { /* 7/16 <=|x|<11/16 */
                            id = 0;
                            x = Fma(2.0, x, -one) / (2.0 + x);
                        }
                        else
                        { /* 11/16<=|x|< 19/16 */
                            id = 1;
                            x = (x - one) / (x + one);
                        }
                    }
                    else
                    {
                        if (ix < 0x40038000)
                        { /* |x| < 2.4375 */
                            id = 2;
                            x = (x - 1.5) / Fma(1.5, x, one);
                        }
                        else
                        { /* 2.4375 <= |x| < 2^66 */
                            id = 3;
                            x = -1.0 / x;
                        }
                    }
                }
                /* end of argument reduction */
                z = x * x;
                w = z * z;
                /* break sum from i=0 to 10 aT[i]z**(i+1) into odd and even poly */
                s1 = z * Fma(w, Fma(w, Fma(w, Fma(w, Fma(w, AtanT[10], AtanT[8]), AtanT[6]), AtanT[4]), AtanT[2]), AtanT[0]);
                s2 = w * Fma(w, Fma(w, Fma(w, Fma(w, AtanT[9], AtanT[7]), AtanT[5]), AtanT[3]), AtanT[1]);
                if (id < 0)
                    return Fma(-x, s1 + s2, x);
                else
                {
                    z = AtanHi[id] - (Fma(x, s1 + s2, -AtanLo[id]) - x);
                    return (hx < 0) ? -z : z;
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbx_sqrt, ufbx_math.c:416-542 (SSE path ufbxm_sqrt)
        // ------------------------------------------------------------------

        public static double Sqrt(double x)
        {
            return Math.Sqrt(x);
        }

        // ------------------------------------------------------------------
        // 2/pi tables and pi/2 reduction, ufbx_math.c:544-1034
        // ------------------------------------------------------------------

        /*
         * Table of constants for 2/pi, 396 Hex digits (476 decimal) of 2/pi
         */
        private static readonly int[] TwoOverPi =
        {
            0xA2F983,
            0x6E4E44,
            0x1529FC,
            0x2757D1,
            0xF534DD,
            0xC0DB62,
            0x95993C,
            0x439041,
            0xFE5163,
            0xABDEBB,
            0xC561B7,
            0x246E3A,
            0x424DD2,
            0xE00649,
            0x2EEA09,
            0xD1921C,
            0xFE1DEB,
            0x1CB129,
            0xA73EE8,
            0x8235F5,
            0x2EBB44,
            0x84E99C,
            0x7026B4,
            0x5F7E41,
            0x3991D6,
            0x398353,
            0x39F49C,
            0x845F8B,
            0xBDF928,
            0x3B1FF8,
            0x97FFDE,
            0x05980F,
            0xEF2F11,
            0x8B5A0A,
            0x6D1F6D,
            0x367ECF,
            0x27CB09,
            0xB74F46,
            0x3F669E,
            0x5FEA2D,
            0x7527BA,
            0xC7EBE5,
            0xF17B3D,
            0x0739F7,
            0x8A5292,
            0xEA6BFB,
            0x5FB11F,
            0x8D5D08,
            0x560330,
            0x46FC7B,
            0x6BABF0,
            0xCFBC20,
            0x9AF436,
            0x1DA9E3,
            0x91615E,
            0xE61B08,
            0x659985,
            0x5F14A0,
            0x68408D,
            0xFFD880,
            0x4D7327,
            0x310606,
            0x1556CA,
            0x73A8C9,
            0x60E27B,
            0xC08C6B,
        };

        private static readonly int[] Npio2Hw =
        {
            0x3FF921FB,
            0x400921FB,
            0x4012D97C,
            0x401921FB,
            0x401F6A7A,
            0x4022D97C,
            0x4025FDBB,
            0x402921FB,
            0x402C463A,
            0x402F6A7A,
            0x4031475C,
            0x4032D97C,
            0x40346B9C,
            0x4035FDBB,
            0x40378FDB,
            0x403921FB,
            0x403AB41B,
            0x403C463A,
            0x403DD85A,
            0x403F6A7A,
            0x40407E4C,
            0x4041475C,
            0x4042106C,
            0x4042D97C,
            0x4043A28C,
            0x40446B9C,
            0x404534AC,
            0x4045FDBB,
            0x4046C6CB,
            0x40478FDB,
            0x404858EB,
            0x404921FB,
        };

        private static readonly int[] KernelRemPio2InitJk = { 2, 3, 4, 6 }; /* initial value for jk */

        private static readonly double[] KernelRemPio2PIo2 =
        {
            1.57079625129699707031e+00, /* 0x3FF921FB, 0x40000000 */
            7.54978941586159635335e-08, /* 0x3E74442D, 0x00000000 */
            5.39030252995776476554e-15, /* 0x3CF84698, 0x80000000 */
            3.28200341580791294123e-22, /* 0x3B78CC51, 0x60000000 */
            1.27065575308067607349e-29, /* 0x39F01B83, 0x80000000 */
            1.22933308981111328932e-36, /* 0x387A2520, 0x40000000 */
            2.73370053816464559624e-44, /* 0x36E38222, 0x80000000 */
            2.16741683877804819444e-51, /* 0x3569F31D, 0x00000000 */
        };

        private static int KernelRemPio2(double[] x, double[] y, int e0, int nx, int prec, int[] ipio2)
        {
            const double zero = 0.0;
            const double one = 1.0;
            const double two24 = 1.67772160000000000000e+07;  /* 0x41700000, 0x00000000 */
            const double twon24 = 5.96046447753906250000e-08; /* 0x3E700000, 0x00000000 */

            unchecked
            {
                int jz, jx, jv, jp, jk, carry, n, i, j, k, m, q0, ih;
                int[] iq = new int[20];
                double z, fw;
                double[] f = new double[20];
                double[] fq = new double[20];
                double[] q = new double[20];

                /* initialize jk */
                jk = KernelRemPio2InitJk[prec];
                jp = jk;

                /* determine jx,jv,q0, note that 3>q0 */
                jx = nx - 1;
                jv = (e0 - 3) / 24;
                if (jv < 0)
                    jv = 0;
                q0 = e0 - 24 * (jv + 1);

                /* set up f[0] to f[jx+jk] where f[jx+jk] = ipio2[jv+jk] */
                j = jv - jx;
                m = jx + jk;
                for (i = 0; i <= m; i++, j++)
                    f[i] = (j < 0) ? zero : (double)ipio2[j];

                /* compute q[0],q[1],...q[jk] */
                for (i = 0; i <= jk; i++)
                {
                    fw = 0.0;
                    for (j = 0; j <= jx; j++)
                        fw = Fma(x[j], f[jx + i - j], fw);
                    q[i] = fw;
                }

                jz = jk;

                for (;;)
                {
                    /* distill q[] into iq[] reversingly */
                    i = 0;
                    j = jz;
                    z = q[jz];
                    for (; j > 0; i++, j--)
                    {
                        fw = (double)(int)(twon24 * z);
                        iq[i] = (int)(z - two24 * fw);
                        z = q[j - 1] + fw;
                    }

                    /* compute n */
                    z = Scalbn(z, q0); /* actual value of z */
                    z -= 8.0 * Floor(z * 0.125); /* trim off integer >= 8 */
                    n = (int)z;
                    z -= (double)n;
                    ih = 0;
                    if (q0 > 0)
                    { /* need iq[jz-1] to determine n */
                        i = iq[jz - 1] >> (24 - q0);
                        n += i;
                        iq[jz - 1] -= i << (24 - q0);
                        ih = iq[jz - 1] >> (23 - q0);
                    }
                    else if (q0 == 0)
                    {
                        ih = iq[jz - 1] >> 23;
                    }
                    else if (z >= 0.5)
                    {
                        ih = 2;
                    }

                    if (ih > 0)
                    { /* q > 0.5 */
                        n += 1;
                        carry = 0;
                        for (i = 0; i < jz; i++)
                        { /* compute 1-q */
                            j = iq[i];
                            if (carry == 0)
                            {
                                if (j != 0)
                                {
                                    carry = 1;
                                    iq[i] = 0x1000000 - j;
                                }
                            }
                            else
                                iq[i] = 0xffffff - j;
                        }
                        if (q0 > 0)
                        { /* rare case: chance is 1 in 12 */
                            switch (q0)
                            {
                                case 1:
                                    iq[jz - 1] &= 0x7fffff;
                                    break;
                                case 2:
                                    iq[jz - 1] &= 0x3fffff;
                                    break;
                                default: break;
                            }
                        }
                        if (ih == 2)
                        {
                            z = one - z;
                            if (carry != 0)
                                z -= Scalbn(one, q0);
                        }
                    }

                    /* check if recomputation is needed */
                    if (z == zero)
                    {
                        j = 0;
                        for (i = jz - 1; i >= jk; i--)
                            j |= iq[i];
                        if (j == 0)
                        { /* need recomputation */
                            for (k = 1; iq[jk - k] == 0; k++)
                                ; /* k = no. of terms needed */

                            for (i = jz + 1; i <= jz + k; i++)
                            { /* add q[jz+1] to q[jz+k] */
                                f[jx + i] = (double)ipio2[jv + i];
                                fw = 0.0;
                                for (j = 0; j <= jx; j++)
                                    fw = Fma(x[j], f[jx + i - j], fw);
                                q[i] = fw;
                            }
                            jz += k;
                            // goto recompute;
                            continue;
                        }
                    }

                    break;
                }

                /* chop off zero terms */
                if (z == 0.0)
                {
                    jz -= 1;
                    q0 -= 24;
                    while (iq[jz] == 0)
                    {
                        jz--;
                        q0 -= 24;
                    }
                }
                else
                { /* break z into 24-bit if necessary */
                    z = Scalbn(z, -q0);
                    if (z >= two24)
                    {
                        fw = (double)(int)(twon24 * z);
                        iq[jz] = (int)(z - two24 * fw);
                        jz += 1;
                        q0 += 24;
                        iq[jz] = (int)fw;
                    }
                    else
                        iq[jz] = (int)z;
                }

                /* convert integer "bit" chunk to floating-point value */
                fw = Scalbn(one, q0);
                for (i = jz; i >= 0; i--)
                {
                    q[i] = fw * (double)iq[i];
                    fw *= twon24;
                }

                /* compute PIo2[0,...,jp]*q[jz,...,0] */
                fq[0] = 0.0; /* dumb warning fix */
                for (i = jz; i >= 0; i--)
                {
                    fw = 0.0;
                    for (k = 0; k <= jp && k <= jz - i; k++)
                        fw = Fma(KernelRemPio2PIo2[k], q[i + k], fw);
                    fq[jz - i] = fw;
                }

                /* compress fq[] into y[] */
                switch (prec)
                {
                    case 0:
                        {
                            fw = 0.0;
                            for (i = jz; i >= 0; i--)
                                fw += fq[i];
                            y[0] = (ih == 0) ? fw : -fw;
                            break;
                        }
                    case 1:
                    case 2:
                        {
                            fw = 0.0;
                            for (i = jz; i >= 0; i--)
                                fw += fq[i];
                            y[0] = (ih == 0) ? fw : -fw;
                            fw = fq[0] - fw;
                            for (i = 1; i <= jz; i++)
                                fw += fq[i];
                            y[1] = (ih == 0) ? fw : -fw;
                            break;
                        }
                    case 3: /* painful */
                        {
                            for (i = jz; i > 0; i--)
                            {
                                fw = fq[i - 1] + fq[i];
                                fq[i] += fq[i - 1] - fw;
                                fq[i - 1] = fw;
                            }
                            for (i = jz; i > 1; i--)
                            {
                                fw = fq[i - 1] + fq[i];
                                fq[i] += fq[i - 1] - fw;
                                fq[i - 1] = fw;
                            }
                            fw = 0.0;
                            for (i = jz; i >= 2; i--)
                                fw += fq[i];
                            if (ih == 0)
                            {
                                y[0] = fq[0];
                                y[1] = fq[1];
                                y[2] = fw;
                            }
                            else
                            {
                                y[0] = -fq[0];
                                y[1] = -fq[1];
                                y[2] = -fw;
                            }
                            break;
                        }
                    default: break;
                }
                return n & 7;
            }
        }

        private static int RemPio2(double x, double[] y)
        {
            const double half = 5.00000000000000000000e-01;    /* 0x3FE00000, 0x00000000 */
            const double two24 = 1.67772160000000000000e+07;   /* 0x41700000, 0x00000000 */
            const double invpio2 = 6.36619772367581382433e-01; /* 0x3FE45F30, 0x6DC9C883 */
            const double pio2_1 = 1.57079632673412561417e+00;  /* 0x3FF921FB, 0x54400000 */
            const double pio2_1t = 6.07710050650619224932e-11; /* 0x3DD0B461, 0x1A626331 */
            const double pio2_2 = 6.07710050630396597660e-11;  /* 0x3DD0B461, 0x1A600000 */
            const double pio2_2t = 2.02226624879595063154e-21; /* 0x3BA3198A, 0x2E037073 */
            const double pio2_3 = 2.02226624871116645580e-21;  /* 0x3BA3198A, 0x2E000000 */
            const double pio2_3t = 8.47842766036889956997e-32; /* 0x397B839A, 0x252049C1 */

            unchecked
            {
                double z, w, t, r, fn;
                double[] tx = new double[3];
                int e0, i, j, nx, n, ix, hx;

                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32)); /* high word of x */
                ix = hx & 0x7fffffff;
                if (ix <= 0x3fe921fb) /* |x| ~<= pi/4 , no need for reduction */
                {
                    y[0] = x;
                    y[1] = 0;
                    return 0;
                }
                if (ix < 0x4002d97c)
                { /* |x| < 3pi/4, special case with n=+-1 */
                    if (hx > 0)
                    {
                        z = x - pio2_1;
                        if (ix != 0x3ff921fb)
                        { /* 33+53 bit pi is good enough */
                            y[0] = z - pio2_1t;
                            y[1] = (z - y[0]) - pio2_1t;
                        }
                        else
                        { /* near pi/2, use 33+33+53 bit pi */
                            z -= pio2_2;
                            y[0] = z - pio2_2t;
                            y[1] = (z - y[0]) - pio2_2t;
                        }
                        return 1;
                    }
                    else
                    { /* negative x */
                        z = x + pio2_1;
                        if (ix != 0x3ff921fb)
                        { /* 33+53 bit pi is good enough */
                            y[0] = z + pio2_1t;
                            y[1] = (z - y[0]) + pio2_1t;
                        }
                        else
                        { /* near pi/2, use 33+33+53 bit pi */
                            z += pio2_2;
                            y[0] = z + pio2_2t;
                            y[1] = (z - y[0]) + pio2_2t;
                        }
                        return -1;
                    }
                }
                if (ix <= 0x413921fb)
                { /* |x| ~<= 2^19*(pi/2), medium size */
                    t = Abs(x);
                    n = (int)Fma(t, invpio2, half);
                    fn = (double)n;
                    r = Fma(-fn, pio2_1, t);
                    w = fn * pio2_1t; /* 1st round good to 85 bit */
                    if (n < 32 && ix != Npio2Hw[n - 1])
                    {
                        y[0] = r - w; /* quick check no cancellation */
                    }
                    else
                    {
                        j = ix >> 20;
                        y[0] = r - w;
                        i = j - ((Hi(y[0]) >> 20) & 0x7ff);
                        if (i > 16)
                        { /* 2nd iteration needed, good to 118 */
                            t = r;
                            w = fn * pio2_2;
                            r = t - w;
                            w = Fma(fn, pio2_2t, -((t - r) - w));
                            y[0] = r - w;
                            i = j - ((Hi(y[0]) >> 20) & 0x7ff);
                            if (i > 49)
                            { /* 3rd iteration need, 151 bits acc */
                                t = r; /* will cover all possible cases */
                                w = fn * pio2_3;
                                r = t - w;
                                w = Fma(fn, pio2_3t, -((t - r) - w));
                                y[0] = r - w;
                            }
                        }
                    }
                    y[1] = (r - y[0]) - w;
                    if (hx < 0)
                    {
                        y[0] = -y[0];
                        y[1] = -y[1];
                        return -n;
                    }
                    else
                        return n;
                }
                /*
                 * all other (large) arguments
                 */
                if (ix >= 0x7ff00000)
                { /* x is inf or NaN */
                    y[0] = x - x;
                    y[1] = x - x;
                    return 0;
                }
                /* set z = scalbn(|x|,ilogb(x)-23) */
                e0 = (ix >> 20) - 1046; /* e0 = ilogb(z)-23; */
                z = FromHiLo(ix - (e0 << 20), (uint)bx);
                for (i = 0; i < 2; i++)
                {
                    tx[i] = (double)(int)z;
                    z = (z - tx[i]) * two24;
                }
                tx[2] = z;
                nx = 3;
                while (tx[nx - 1] == 0.0)
                    nx--; /* skip zero term */
                n = KernelRemPio2(tx, y, e0, nx, 2, TwoOverPi);
                if (hx < 0)
                {
                    y[0] = -y[0];
                    y[1] = -y[1];
                    return -n;
                }
                return n;
            }
        }

        // ------------------------------------------------------------------
        // ufbxm_kernel_sin, ufbx_math.c:1036-1063
        // ------------------------------------------------------------------

        private static double KernelSin(double x, double y, int iy)
        {
            const double half = 5.00000000000000000000e-01; /* 0x3FE00000, 0x00000000 */
            const double S1 = -1.66666666666666324348e-01;  /* 0xBFC55555, 0x55555549 */
            const double S2 = 8.33333333332248946124e-03;   /* 0x3F811111, 0x1110F8A6 */
            const double S3 = -1.98412698298579493134e-04;  /* 0xBF2A01A0, 0x19C161D5 */
            const double S4 = 2.75573137070700676789e-06;   /* 0x3EC71DE3, 0x57B1FE7D */
            const double S5 = -2.50507602534068634195e-08;  /* 0xBE5AE5E6, 0x8A2B9CEB */
            const double S6 = 1.58969099521155010221e-10;   /* 0x3DE5D93A, 0x5ACFD57C */

            unchecked
            {
                int ix;
                ix = Hi(x) & 0x7fffffff; /* high word of x */
                if (ix < 0x3e400000) /* |x| < 2**-27 */
                {
                    if ((int)x == 0)
                        return x;
                } /* generate inexact */
                double z = x * x;
                double v = z * x;
                double r = Fma(z, Fma(z, Fma(z, Fma(z, S6, S5), S4), S3), S2);
                if (iy == 0)
                    return Fma(v, Fma(z, r, S1), x);
                else
                    return x - Fma(-v, S1, Fma(z, half * y - v * r, -y));
            }
        }

        // ------------------------------------------------------------------
        // ufbxm_kernel_cos, ufbx_math.c:1065-1102
        // ------------------------------------------------------------------

        private static double KernelCos(double x, double y)
        {
            const double one = 1.00000000000000000000e+00; /* 0x3FF00000, 0x00000000 */
            const double C1 = 4.16666666666666019037e-02;  /* 0x3FA55555, 0x5555554C */
            const double C2 = -1.38888888888741095749e-03; /* 0xBF56C16C, 0x16C15177 */
            const double C3 = 2.48015872894767294178e-05;  /* 0x3EFA01A0, 0x19CB1590 */
            const double C4 = -2.75573143513906633035e-07; /* 0xBE927E4F, 0x809C52AD */
            const double C5 = 2.08757232129817482790e-09;  /* 0x3E21EE9E, 0xBDB4B1C4 */
            const double C6 = -1.13596475577881948265e-11; /* 0xBDA8FAE9, 0xBE8838D4 */

            unchecked
            {
                int ix;
                ix = Hi(x) & 0x7fffffff; /* ix = |x|'s high word */
                if (ix < 0x3e400000)
                { /* if x < 2**27 */
                    if ((int)x == 0)
                        return one; /* generate inexact */
                }
                double z = x * x;
                double r = z * Fma(z, Fma(z, Fma(z, Fma(z, Fma(z, C6, C5), C4), C3), C2), C1);
                if (ix < 0x3FD33333) /* if |x| < 0.3 */
                    return one - Fma(0.5, z, -(z * r - x * y));
                else
                {
                    double qx;
                    if (ix > 0x3fe90000)
                    { /* x > 0.78125 */
                        qx = 0.28125;
                    }
                    else
                    {
                        qx = FromHiLo(ix - 0x00200000, 0u); /* x/4 */
                    }
                    double hz = Fma(0.5, z, -qx);
                    double a = one - qx;
                    return a - (hz - (z * r - x * y));
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbxm_kernel_tan, ufbx_math.c:1104-1211
        // ------------------------------------------------------------------

        private static readonly double[] TanXxx =
        {
            3.33333333333334091986e-01,             /* 3FD55555, 55555563 */
            1.33333333333201242699e-01,             /* 3FC11111, 1110FE7A */
            5.39682539762260521377e-02,             /* 3FABA1BA, 1BB341FE */
            2.18694882948595424599e-02,             /* 3F9664F4, 8406D637 */
            8.86323982359930005737e-03,             /* 3F8226E3, E96E8493 */
            3.59207910759131235356e-03,             /* 3F6D6D22, C9560328 */
            1.45620945432529025516e-03,             /* 3F57DBC8, FEE08315 */
            5.88041240820264096874e-04,             /* 3F4344D8, F2F26501 */
            2.46463134818469906812e-04,             /* 3F3026F7, 1A8D1068 */
            7.81794442939557092300e-05,             /* 3F147E88, A03792A6 */
            7.14072491382608190305e-05,             /* 3F12B80F, 32F0A7E9 */
            -1.85586374855275456654e-05,            /* BEF375CB, DB605373 */
            2.59073051863633712884e-05,             /* 3EFB2A70, 74BF7AD4 */
            /* one */ 1.00000000000000000000e+00,    /* 3FF00000, 00000000 */
            /* pio4 */ 7.85398163397448278999e-01,  /* 3FE921FB, 54442D18 */
            /* pio4lo */ 3.06161699786838301793e-17 /* 3C81A626, 33145C07 */
        };

        private static double KernelTan(double x, double y, int iy)
        {
            /* one, pio4 and pio4lo live at TanXxx[13..15] in the C source */
            const double one = 1.00000000000000000000e+00;
            const double pio4 = 7.85398163397448278999e-01;
            const double pio4lo = 3.06161699786838301793e-17;

            unchecked
            {
                double z, r, v, w, s;
                int ix, hx;

                double[] T = TanXxx;

                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32)); /* high word of x */
                ix = hx & 0x7fffffff; /* high word of |x| */
                if (ix < 0x3e300000)
                { /* x < 2**-28 */
                    if ((int)x == 0)
                    { /* generate inexact */
                        if (((ix | unchecked((int)(uint)bx)) | (iy + 1)) == 0)
                            return one / Abs(x);
                        else
                        {
                            if (iy == 1)
                                return x;
                            else
                            { /* compute -1 / (x+y) carefully */
                                double a, t;

                                z = w = x + y;
                                z = ZeroLo(z);
                                v = y - (z - x);
                                t = a = -one / w;
                                t = ZeroLo(t);
                                s = Fma(t, z, one);
                                return Fma(a, Fma(t, v, s), t);
                            }
                        }
                    }
                }
                if (ix >= 0x3FE59428)
                { /* |x| >= 0.6744 */
                    if (hx < 0)
                    {
                        x = -x;
                        y = -y;
                    }
                    z = pio4 - x;
                    w = pio4lo - y;
                    x = z + w;
                    y = 0.0;
                }
                z = x * x;
                w = z * z;
                /*
                 * Break x^5*(T[1]+x^2*T[2]+...) into
                 * x^5(T[1]+x^4*T[3]+...+x^20*T[11]) +
                 * x^5(x^2*(T[2]+x^4*T[4]+...+x^22*[T12]))
                 */
                r = Fma(w, Fma(w, Fma(w, Fma(w, Fma(w, T[11], T[9]), T[7]), T[5]), T[3]), T[1]);
                v = z * Fma(w, Fma(w, Fma(w, Fma(w, Fma(w, T[12], T[10]), T[8]), T[6]), T[4]), T[2]);
                s = z * x;
                r = Fma(z, Fma(s, r + v, y), y);
                r = Fma(T[0], s, r);
                w = x + r;
                if (ix >= 0x3FE59428)
                {
                    v = (double)iy;
                    return (double)(1 - ((hx >> 30) & 2)) *
                           Fma(-2.0, x - (w * w / (w + v) - r), v);
                }
                if (iy == 1)
                    return w;
                else
                {
                    /*
                     * if allow error up to 2 ulp, simply return
                     * -1.0 / (x+r) here
                     */
                    /* compute -1.0 / (x+r) accurately */
                    double a, t;
                    z = w;
                    z = ZeroLo(z);
                    v = r - (z - x); /* z+v = r+x */
                    t = a = -1.0 / w; /* a = -1.0/w */
                    t = ZeroLo(t);
                    s = Fma(t, z, 1.0);
                    return Fma(a, Fma(t, v, s), t);
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbx_sin, ufbx_math.c:1213-1246
        // ------------------------------------------------------------------

        public static double Sin(double x)
        {
            double[] y = new double[2];
            double z = 0.0;

            unchecked
            {
                int n, ix;

                /* High word of x. */
                ix = Hi(x);

                /* |x| ~< pi/4 */
                ix &= 0x7fffffff;
                if (ix <= 0x3fe921fb)
                    return KernelSin(x, z, 0);

                /* sin(Inf or NaN) is NaN */
                else if (ix >= 0x7ff00000)
                    return x - x;

                /* argument reduction needed */
                else
                {
                    n = RemPio2(x, y);
                    switch (n & 3)
                    {
                        case 0:
                            return KernelSin(y[0], y[1], 1);
                        case 1:
                            return KernelCos(y[0], y[1]);
                        case 2:
                            return -KernelSin(y[0], y[1], 1);
                        default:
                            return -KernelCos(y[0], y[1]);
                    }
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbx_cos, ufbx_math.c:1248-1281
        // ------------------------------------------------------------------

        public static double Cos(double x)
        {
            double[] y = new double[2];
            double z = 0.0;

            unchecked
            {
                int n, ix;

                /* High word of x. */
                ix = Hi(x);

                /* |x| ~< pi/4 */
                ix &= 0x7fffffff;
                if (ix <= 0x3fe921fb)
                    return KernelCos(x, z);

                /* cos(Inf or NaN) is NaN */
                else if (ix >= 0x7ff00000)
                    return x - x;

                /* argument reduction needed */
                else
                {
                    n = RemPio2(x, y);
                    switch (n & 3)
                    {
                        case 0:
                            return KernelCos(y[0], y[1]);
                        case 1:
                            return -KernelSin(y[0], y[1], 1);
                        case 2:
                            return -KernelCos(y[0], y[1]);
                        default:
                            return KernelSin(y[0], y[1], 1);
                    }
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbx_tan, ufbx_math.c:1283-1307
        // ------------------------------------------------------------------

        public static double Tan(double x)
        {
            double[] y = new double[2];
            double z = 0.0;

            unchecked
            {
                int n, ix;

                /* High word of x. */
                ix = Hi(x);

                /* |x| ~< pi/4 */
                ix &= 0x7fffffff;
                if (ix <= 0x3fe921fb)
                    return KernelTan(x, z, 1);

                /* tan(Inf or NaN) is NaN */
                else if (ix >= 0x7ff00000)
                    return x - x; /* NaN */

                /* argument reduction needed */
                else
                {
                    n = RemPio2(x, y);
                    return KernelTan(y[0], y[1], 1 - ((n & 1) << 1)); /*   1 -- n even
                                                              -1 -- n odd */
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbx_asin, ufbx_math.c:1309-1380
        // ------------------------------------------------------------------

        public static double Asin(double x) /* wrapper asin */
        {
            const double one = 1.00000000000000000000e+00; /* 0x3FF00000, 0x00000000 */
            const double huge = 1.000e+300;
            const double pio2_hi = 1.57079632679489655800e+00; /* 0x3FF921FB, 0x54442D18 */
            const double pio2_lo = 6.12323399573676603587e-17; /* 0x3C91A626, 0x33145C07 */
            const double pio4_hi = 7.85398163397448278999e-01; /* 0x3FE921FB, 0x54442D18 */
            /* coefficient for R(x^2) */
            const double pS0 = 1.66666666666666657415e-01;     /* 0x3FC55555, 0x55555555 */
            const double pS1 = -3.25565818622400915405e-01;    /* 0xBFD4D612, 0x03EB6F7D */
            const double pS2 = 2.01212532134862925881e-01;     /* 0x3FC9C155, 0x0E884455 */
            const double pS3 = -4.00555345006794114027e-02;    /* 0xBFA48228, 0xB5688F3B */
            const double pS4 = 7.91534994289814532176e-04;     /* 0x3F49EFE0, 0x7501B288 */
            const double pS5 = 3.47933107596021167570e-05;     /* 0x3F023DE1, 0x0DFDF709 */
            const double qS1 = -2.40339491173441421878e+00;    /* 0xC0033A27, 0x1C8A2D4B */
            const double qS2 = 2.02094576023350569471e+00;     /* 0x40002AE5, 0x9C598AC8 */
            const double qS3 = -6.88283971605453293030e-01;    /* 0xBFE6066C, 0x1B8D0159 */
            const double qS4 = 7.70381505559019352791e-02;     /* 0x3FB3B8C5, 0xB12E9282 */

            unchecked
            {
                double t = 0.0, w, p, q, c, r, s;
                int hx, ix;
                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32));
                ix = hx & 0x7fffffff;
                if (ix >= 0x3ff00000)
                { /* |x|>= 1 */
                    if (((ix - 0x3ff00000) | unchecked((int)(uint)bx)) == 0)
                        /* asin(1)=+-pi/2 with inexact */
                        return x * pio2_hi + x * pio2_lo;
                    return (x - x) / (x - x); /* asin(|x|>1) is NaN */
                }
                else if (ix < 0x3fe00000)
                { /* |x|<0.5 */
                    if (ix < 0x3e400000)
                    { /* if |x| < 2**-27 */
                        if (huge + x > one)
                            return x; /* return x with inexact if x!=0 */
                    }
                    else
                        t = x * x;
                    p = t * (pS0 + t * (pS1 + t * (pS2 + t * (pS3 + t * (pS4 + t * pS5)))));
                    q = one + t * (qS1 + t * (qS2 + t * (qS3 + t * qS4)));
                    w = p / q;
                    return x + x * w;
                }
                /* 1> |x|>= 0.5 */
                w = one - Abs(x);
                t = w * 0.5;
                p = t * (pS0 + t * (pS1 + t * (pS2 + t * (pS3 + t * (pS4 + t * pS5)))));
                q = one + t * (qS1 + t * (qS2 + t * (qS3 + t * qS4)));
                s = Sqrt(t);
                if (ix >= 0x3FEF3333)
                { /* if |x| > 0.975 */
                    w = p / q;
                    t = pio2_hi - (2.0 * (s + s * w) - pio2_lo);
                }
                else
                {
                    w = s;
                    w = ZeroLo(w);
                    c = (t - w * w) / (s + w);
                    r = p / q;
                    p = 2.0 * s * r - (pio2_lo - 2.0 * c);
                    q = pio4_hi - 2.0 * w;
                    t = pio4_hi - (p - q);
                }
                if (hx > 0)
                    return t;
                else
                    return -t;
            }
        }

        // ------------------------------------------------------------------
        // ufbx_acos, ufbx_math.c:1382-1449
        // ------------------------------------------------------------------

        public static double Acos(double x) /* wrapper acos */
        {
            const double one = 1.00000000000000000000e+00;     /* 0x3FF00000, 0x00000000 */
            const double pi = 3.14159265358979311600e+00;      /* 0x400921FB, 0x54442D18 */
            const double pio2_hi = 1.57079632679489655800e+00; /* 0x3FF921FB, 0x54442D18 */
            const double pio2_lo = 6.12323399573676603587e-17; /* 0x3C91A626, 0x33145C07 */
            const double pS0 = 1.66666666666666657415e-01;     /* 0x3FC55555, 0x55555555 */
            const double pS1 = -3.25565818622400915405e-01;    /* 0xBFD4D612, 0x03EB6F7D */
            const double pS2 = 2.01212532134862925881e-01;     /* 0x3FC9C155, 0x0E884455 */
            const double pS3 = -4.00555345006794114027e-02;    /* 0xBFA48228, 0xB5688F3B */
            const double pS4 = 7.91534994289814532176e-04;     /* 0x3F49EFE0, 0x7501B288 */
            const double pS5 = 3.47933107596021167570e-05;     /* 0x3F023DE1, 0x0DFDF709 */
            const double qS1 = -2.40339491173441421878e+00;    /* 0xC0033A27, 0x1C8A2D4B */
            const double qS2 = 2.02094576023350569471e+00;     /* 0x40002AE5, 0x9C598AC8 */
            const double qS3 = -6.88283971605453293030e-01;    /* 0xBFE6066C, 0x1B8D0159 */
            const double qS4 = 7.70381505559019352791e-02;     /* 0x3FB3B8C5, 0xB12E9282 */

            unchecked
            {
                double z, p, q, r, w, s, c, df;
                int hx, ix;
                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32));
                ix = hx & 0x7fffffff;
                if (ix >= 0x3ff00000)
                { /* |x| >= 1 */
                    if (((ix - 0x3ff00000) | unchecked((int)(uint)bx)) == 0)
                    { /* |x|==1 */
                        if (hx > 0)
                            return 0.0; /* acos(1) = 0 */
                        else
                            return pi + 2.0 * pio2_lo; /* acos(-1)= pi */
                    }
                    return (x - x) / (x - x); /* acos(|x|>1) is NaN */
                }
                if (ix < 0x3fe00000)
                { /* |x| < 0.5 */
                    if (ix <= 0x3c600000)
                        return pio2_hi + pio2_lo; /* if |x|<2**-57 */
                    z = x * x;
                    p = z * (pS0 + z * (pS1 + z * (pS2 + z * (pS3 + z * (pS4 + z * pS5)))));
                    q = one + z * (qS1 + z * (qS2 + z * (qS3 + z * qS4)));
                    r = p / q;
                    return pio2_hi - (x - (pio2_lo - x * r));
                }
                else if (hx < 0)
                { /* x < -0.5 */
                    z = (one + x) * 0.5;
                    p = z * (pS0 + z * (pS1 + z * (pS2 + z * (pS3 + z * (pS4 + z * pS5)))));
                    q = one + z * (qS1 + z * (qS2 + z * (qS3 + z * qS4)));
                    s = Sqrt(z);
                    r = p / q;
                    w = r * s - pio2_lo;
                    return pi - 2.0 * (s + w);
                }
                else
                { /* x > 0.5 */
                    z = (one - x) * 0.5;
                    s = Sqrt(z);
                    df = s;
                    df = ZeroLo(df);
                    c = (z - df * df) / (s + df);
                    p = z * (pS0 + z * (pS1 + z * (pS2 + z * (pS3 + z * (pS4 + z * pS5)))));
                    q = one + z * (qS1 + z * (qS2 + z * (qS3 + z * qS4)));
                    r = p / q;
                    w = r * s + c;
                    return 2.0 * (df + w);
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbx_atan2, ufbx_math.c:1451-1556
        // ------------------------------------------------------------------

        public static double Atan2(double y, double x) /* wrapper atan2 */
        {
            const double tiny = 1.0e-300;
            const double zero = 0.0;
            const double pi_o_4 = 7.8539816339744827900E-01; /* 0x3FE921FB, 0x54442D18 */
            const double pi_o_2 = 1.5707963267948965580E+00; /* 0x3FF921FB, 0x54442D18 */
            const double pi = 3.1415926535897931160E+00;     /* 0x400921FB, 0x54442D18 */
            const double pi_lo = 1.2246467991473531772E-16;  /* 0x3CA1A626, 0x33145C07 */

            unchecked
            {
                double z;
                int k, m, hx, hy, ix, iy;
                uint lx, ly;
                ulong bx = ToBits(x);
                ulong by = ToBits(y);

                hx = unchecked((int)(uint)(bx >> 32));
                lx = (uint)bx;
                hy = unchecked((int)(uint)(by >> 32));
                ly = (uint)by;
                ix = hx & 0x7fffffff;
                iy = hy & 0x7fffffff;
                if ((((uint)ix | (((lx | (uint)(-(int)lx)) >> 31))) > 0x7ff00000u) ||
                    (((uint)iy | (((ly | (uint)(-(int)ly)) >> 31))) > 0x7ff00000u)) /* x or y is NaN */
                    return x + y;
                if (((hx - 0x3ff00000) | unchecked((int)lx)) == 0)
                    return Atan(y); /* x=1.0 */
                m = ((hy >> 31) & 1) | ((hx >> 30) & 2); /* 2*sign(x)+sign(y) */

                /* when y = 0 */
                if ((iy | unchecked((int)ly)) == 0)
                {
                    switch (m)
                    {
                        case 0:
                        case 1:
                            return y; /* atan(+-0,+anything)=+-0 */
                        case 2:
                            return pi + tiny; /* atan(+0,-anything) = pi */
                        case 3:
                            return -pi - tiny; /* atan(-0,-anything) =-pi */
                        default: break;
                    }
                }
                /* when x = 0 */
                if ((ix | unchecked((int)lx)) == 0)
                    return (hy < 0) ? -pi_o_2 - tiny : pi_o_2 + tiny;

                /* when x is INF */
                if (ix == 0x7ff00000)
                {
                    if (iy == 0x7ff00000)
                    {
                        switch (m)
                        {
                            case 0:
                                return pi_o_4 + tiny; /* atan(+INF,+INF) */
                            case 1:
                                return -pi_o_4 - tiny; /* atan(-INF,+INF) */
                            case 2:
                                return 3.0 * pi_o_4 + tiny; /* atan(+INF,-INF) */
                            case 3:
                                return -3.0 * pi_o_4 - tiny; /* atan(-INF,-INF) */
                            default: break;
                        }
                    }
                    else
                    {
                        switch (m)
                        {
                            case 0:
                                return zero; /* atan(+...,+INF) */
                            case 1:
                                return -zero; /* atan(-...,+INF) */
                            case 2:
                                return pi + tiny; /* atan(+...,-INF) */
                            case 3:
                                return -pi - tiny; /* atan(-...,-INF) */
                            default: break;
                        }
                    }
                }
                /* when y is INF */
                if (iy == 0x7ff00000)
                    return (hy < 0) ? -pi_o_2 - tiny : pi_o_2 + tiny;

                /* compute y/x */
                k = (iy - ix) >> 20;
                if (k > 60)
                    z = pi_o_2 + 0.5 * pi_lo; /* |y/x| >  2**60 */
                else if (hx < 0 && k < -60)
                    z = 0.0; /* |y|/x < -2**60 */
                else
                    z = Atan(Abs(y / x)); /* safe to do y/x */
                switch (m)
                {
                    case 0:
                        return z; /* atan(+,+) */
                    case 1:
                        return -z; /* atan(-,+) */
                    case 2:
                        return pi - (z - pi_lo); /* atan(+,-) */
                    default: /* case 3 */
                        return (z - pi_lo) - pi; /* atan(-,-) */
                }
            }
        }

        // ------------------------------------------------------------------
        // ufbx_pow, ufbx_math.c:1558-1864
        // ------------------------------------------------------------------

        private static readonly double[] PowBp = { 1.0, 1.5 };

        private static readonly double[] PowDpH =
        {
            0.0,
            5.84962487220764160156e-01, /* 0x3FE2B803, 0x40000000 */
        };

        private static readonly double[] PowDpL =
        {
            0.0,
            1.35003920212974897128e-08, /* 0x3E4CFDEB, 0x43CFD006 */
        };

        public static double Pow(double x, double y) /* wrapper pow */
        {
            double[] bp = PowBp;
            double[] dp_h = PowDpH;
            double[] dp_l = PowDpL;

            const double zero = 0.0, one = 1.0, two = 2.0, two53 = 9007199254740992.0; /* 0x43400000, 0x00000000 */
            const double huge = 1.0e300, tiny = 1.0e-300;
            /* poly coefs for (3/2)*(log(x)-2s-2/3*s**3 */
            const double L1 = 5.99999999999994648725e-01;      /* 0x3FE33333, 0x33333303 */
            const double L2 = 4.28571428578550184252e-01;      /* 0x3FDB6DB6, 0xDB6FABFF */
            const double L3 = 3.33333329818377432918e-01;      /* 0x3FD55555, 0x518F264D */
            const double L4 = 2.72728123808534006489e-01;      /* 0x3FD17460, 0xA91D4101 */
            const double L5 = 2.30660745775561754067e-01;      /* 0x3FCD864A, 0x93C9DB65 */
            const double L6 = 2.06975017800338417784e-01;      /* 0x3FCA7E28, 0x4A454EEF */
            const double P1 = 1.66666666666666019037e-01;      /* 0x3FC55555, 0x5555553E */
            const double P2 = -2.77777777770155933842e-03;     /* 0xBF66C16C, 0x16BEBD93 */
            const double P3 = 6.61375632143793436117e-05;      /* 0x3F11566A, 0xAF25DE2C */
            const double P4 = -1.65339022054652515390e-06;     /* 0xBEBBBD41, 0xC5D26BF1 */
            const double P5 = 4.13813679705723846039e-08;      /* 0x3E663769, 0x72BEA4D0 */
            const double lg2 = 6.93147180559945286227e-01;     /* 0x3FE62E42, 0xFEFA39EF */
            const double lg2_h = 6.93147182464599609375e-01;   /* 0x3FE62E43, 0x00000000 */
            const double lg2_l = -1.90465429995776804525e-09;  /* 0xBE205C61, 0x0CA86C39 */
            const double ovt = 8.0085662595372944372e-17;      /* -(1024-log2(ovfl+.5ulp)) */
            const double cp = 9.61796693925975554329e-01;      /* 0x3FEEC709, 0xDC3A03FD =2/(3ln2) */
            const double cp_h = 9.61796700954437255859e-01;    /* 0x3FEEC709, 0xE0000000 =(float)cp */
            const double cp_l = -7.02846165095275826516e-09;   /* 0xBE3E2FE0, 0x145B01F5 =tail of cp_h */
            const double ivln2 = 1.44269504088896338700e+00;   /* 0x3FF71547, 0x652B82FE =1/ln2 */
            const double ivln2_h = 1.44269502162933349609e+00; /* 0x3FF71547, 0x60000000 =24b 1/ln2 */
            const double ivln2_l = 1.92596299112661746887e-08; /* 0x3E54AE0B, 0xF85DDF44 =1/ln2 tail */

            unchecked
            {
                double z, ax, z_h, z_l, p_h, p_l;
                double y1, t1, t2, r, s, t, u, v, w;
                int i, j, k, yisint, n;
                int hx, hy, ix, iy;
                uint lx, ly;
                ulong bx = ToBits(x);
                ulong by = ToBits(y);
                ulong bz;

                hx = unchecked((int)(uint)(bx >> 32));
                lx = (uint)bx;
                hy = unchecked((int)(uint)(by >> 32));
                ly = (uint)by;
                ix = hx & 0x7fffffff;
                iy = hy & 0x7fffffff;

                /* y==zero: x**0 = 1 */
                if ((iy | unchecked((int)ly)) == 0)
                    return one;

                /* +-NaN return x+y */
                if (ix > 0x7ff00000 || ((ix == 0x7ff00000) && (lx != 0)) ||
                    iy > 0x7ff00000 || ((iy == 0x7ff00000) && (ly != 0)))
                    return x + y;

                /* determine if y is an odd int when x < 0
                 * yisint = 0  ... y is not an integer
                 * yisint = 1  ... y is an odd int
                 * yisint = 2  ... y is an even int
                 */
                yisint = 0;
                if (hx < 0)
                {
                    if (iy >= 0x43400000)
                        yisint = 2; /* even integer y */
                    else if (iy >= 0x3ff00000)
                    {
                        k = (iy >> 20) - 0x3ff; /* exponent */
                        if (k > 20)
                        {
                            j = unchecked((int)(ly >> (52 - k)));
                            if ((j << (52 - k)) == unchecked((int)ly))
                                yisint = 2 - (j & 1);
                        }
                        else if (ly == 0)
                        {
                            j = iy >> (20 - k);
                            if ((j << (20 - k)) == iy)
                                yisint = 2 - (j & 1);
                        }
                    }
                }

                /* special value of y */
                if (ly == 0)
                {
                    if (iy == 0x7ff00000)
                    { /* y is +-inf */
                        if (((ix - 0x3ff00000) | unchecked((int)lx)) == 0)
                            return y - y; /* inf**+-1 is NaN */
                        else if (ix >= 0x3ff00000) /* (|x|>1)**+-inf = inf,0 */
                            return (hy >= 0) ? y : zero;
                        else /* (|x|<1)**-,+inf = inf,0 */
                            return (hy < 0) ? -y : zero;
                    }
                    if (iy == 0x3ff00000)
                    { /* y is  +-1 */
                        if (hy < 0)
                            return one / x;
                        else
                            return x;
                    }
                    if (hy == 0x40000000)
                        return x * x; /* y is  2 */
                    if (hy == 0x3fe00000)
                    { /* y is  0.5 */
                        if (hx >= 0) /* x >= +0 */
                            return Sqrt(x);
                    }
                }

                ax = Abs(x);
                /* special value of x */
                if (lx == 0)
                {
                    if (ix == 0x7ff00000 || ix == 0 || ix == 0x3ff00000)
                    {
                        z = ax; /* x is +-0,+-inf,+-1 */
                        if (hy < 0)
                            z = one / z; /* z = (1/|x|) */
                        if (hx < 0)
                        {
                            if (((ix - 0x3ff00000) | yisint) == 0)
                            {
                                z = (z - z) / (z - z); /* (-1)**non-int is NaN */
                            }
                            else if (yisint == 1)
                                z = -z; /* (x<0)**odd = -(|x|**odd) */
                        }
                        return z;
                    }
                }

                n = (hx >> 31) + 1;

                /* (x<0)**(non-int) is NaN */
                if ((n | yisint) == 0)
                    return (x - x) / (x - x);

                s = one; /* s (sign of result -ve**odd) = -1 else = 1 */
                if ((n | (yisint - 1)) == 0)
                    s = -one; /* (-ve)**(odd int) */

                /* |y| is huge */
                if (iy > 0x41e00000)
                { /* if |y| > 2**31 */
                    if (iy > 0x43f00000)
                    { /* if |y| > 2**64, must o/uflow */
                        if (ix <= 0x3fefffff)
                            return (hy < 0) ? huge * huge : tiny * tiny;
                        if (ix >= 0x3ff00000)
                            return (hy > 0) ? huge * huge : tiny * tiny;
                    }
                    /* over/underflow if x is not close to one */
                    if (ix < 0x3fefffff)
                        return (hy < 0) ? s * huge * huge : s * tiny * tiny;
                    if (ix > 0x3ff00000)
                        return (hy > 0) ? s * huge * huge : s * tiny * tiny;
                    /* now |1-x| is tiny <= 2**-20, suffice to compute
                       log(x) by x-x^2/2+x^3/3-x^4/4 */
                    t = ax - one; /* t has 20 trailing zeros */
                    w = (t * t) * (0.5 - t * (0.3333333333333333333333 - t * 0.25));
                    u = ivln2_h * t; /* ivln2_h has 21 sig. bits */
                    v = t * ivln2_l - w * ivln2;
                    t1 = u + v;
                    t1 = ZeroLo(t1);
                    t2 = v - (t1 - u);
                }
                else
                {
                    double ss, s2, s_h, s_l, t_h, t_l;
                    n = 0;
                    /* take care subnormal number */
                    if (ix < 0x00100000)
                    {
                        ax *= two53;
                        n -= 53;
                        ix = Hi(ax);
                    }
                    n += (ix >> 20) - 0x3ff;
                    j = ix & 0x000fffff;
                    /* determine interval */
                    ix = j | 0x3ff00000; /* normalize ix */
                    if (j <= 0x3988E)
                        k = 0; /* |x|<sqrt(3/2) */
                    else if (j < 0xBB67A)
                        k = 1; /* |x|<sqrt(3)   */
                    else
                    {
                        k = 0;
                        n += 1;
                        ix -= 0x00100000;
                    }
                    ax = SetHi(ax, ix);

                    /* compute ss = s_h+s_l = (x-1)/(x+1) or (x-1.5)/(x+1.5) */
                    u = ax - bp[k]; /* bp[0]=1.0, bp[1]=1.5 */
                    v = one / (ax + bp[k]);
                    ss = u * v;
                    s_h = ss;
                    s_h = ZeroLo(s_h);
                    /* t_h=ax+bp[k] High */
                    t_h = zero;
                    t_h = SetHi(t_h, ((ix >> 1) | 0x20000000) + 0x00080000 + (k << 18));
                    t_l = ax - (t_h - bp[k]);
                    s_l = v * ((u - s_h * t_h) - s_h * t_l);
                    /* compute log(ax) */
                    s2 = ss * ss;
                    r = s2 * s2 * (L1 + s2 * (L2 + s2 * (L3 + s2 * (L4 + s2 * (L5 + s2 * L6)))));
                    r += s_l * (s_h + ss);
                    s2 = s_h * s_h;
                    t_h = 3.0 + s2 + r;
                    t_h = ZeroLo(t_h);
                    t_l = r - ((t_h - 3.0) - s2);
                    /* u+v = ss*(1+...) */
                    u = s_h * t_h;
                    v = s_l * t_h + t_l * ss;
                    /* 2/(3log2)*(ss+...) */
                    p_h = u + v;
                    p_h = ZeroLo(p_h);
                    p_l = v - (p_h - u);
                    z_h = cp_h * p_h; /* cp_h+cp_l = 2/(3*log2) */
                    z_l = cp_l * p_h + p_l * cp + dp_l[k];
                    /* log2(ax) = (ss+..)*2/(3*log2) = n + dp_h + z_h + z_l */
                    t = (double)n;
                    t1 = (((z_h + z_l) + dp_h[k]) + t);
                    t1 = ZeroLo(t1);
                    t2 = z_l - (((t1 - t) - dp_h[k]) - z_h);
                }

                /* split up y into y1+y2 and compute (y1+y2)*(t1+t2) */
                y1 = y;
                y1 = ZeroLo(y1);
                p_l = (y - y1) * t1 + y * t2;
                p_h = y1 * t1;
                z = p_l + p_h;
                bz = ToBits(z);
                j = unchecked((int)(uint)(bz >> 32));
                i = unchecked((int)(uint)bz);
                if (j >= 0x40900000)
                { /* z >= 1024 */
                    if (((j - 0x40900000) | i) != 0) /* if z > 1024 */
                        return s * huge * huge; /* overflow */
                    else
                    {
                        if (p_l + ovt > z - p_h)
                            return s * huge * huge; /* overflow */
                    }
                }
                else if ((j & 0x7fffffff) >= 0x4090cc00)
                { /* z <= -1075 */
                    if (((j - unchecked((int)0xc090cc00u)) | i) != 0) /* z < -1075 */
                        return s * tiny * tiny; /* underflow */
                    else
                    {
                        if (p_l <= z - p_h)
                            return s * tiny * tiny; /* underflow */
                    }
                }
                /*
                 * compute 2**(p_h+p_l)
                 */
                i = j & 0x7fffffff;
                k = (i >> 20) - 0x3ff;
                n = 0;
                if (i > 0x3fe00000)
                { /* if |z| > 0.5, set n = [z+0.5] */
                    n = j + (0x00100000 >> (k + 1));
                    k = ((n & 0x7fffffff) >> 20) - 0x3ff; /* new k for n */
                    t = zero;
                    t = SetHi(t, n & ~(0x000fffff >> k));
                    n = ((n & 0x000fffff) | 0x00100000) >> (20 - k);
                    if (j < 0)
                        n = -n;
                    p_h -= t;
                }
                t = p_l + p_h;
                t = ZeroLo(t);
                u = t * lg2_h;
                v = (p_l - (t - p_h)) * lg2 + t * lg2_l;
                z = u + v;
                w = v - (z - u);
                t = z * z;
                t1 = z - t * (P1 + t * (P2 + t * (P3 + t * (P4 + t * P5))));
                r = (z * t1) / (t1 - two) - (w + z * w);
                z = one - (r - z);
                j = Hi(z);
                j += (n << 20);
                if ((j >> 20) <= 0)
                {
                    z = Scalbn(z, n); /* subnormal output */
                }
                else
                {
                    bz = ToBits(z);
                    int bzh = unchecked((int)(uint)(bz >> 32));
                    bzh += (n << 20);
                    z = FromHiLo(bzh, (uint)bz);
                }
                return s * z;
            }
        }

        // ------------------------------------------------------------------
        // ufbx_fmin, ufbx_math.c:1866-1869
        // ------------------------------------------------------------------

        public static double FMin(double a, double b)
        {
            return a < b ? a : b;
        }

        // ------------------------------------------------------------------
        // ufbx_fmax, ufbx_math.c:1871-1874
        // ------------------------------------------------------------------

        public static double FMax(double a, double b)
        {
            return a < b ? b : a;
        }

        // ------------------------------------------------------------------
        // ufbx_nextafter, ufbx_math.c:1876-1946
        // ------------------------------------------------------------------

        public static double NextAfter(double x, double y)
        {
            unchecked
            {
                int hx, hy, ix, iy;
                uint lx, ly;
                ulong bx = ToBits(x);
                ulong by = ToBits(y);

                hx = unchecked((int)(uint)(bx >> 32)); /* high word of x */
                lx = (uint)bx; /* low  word of x */
                hy = unchecked((int)(uint)(by >> 32)); /* high word of y */
                ly = (uint)by; /* low  word of y */
                ix = hx & 0x7fffffff; /* |x| */
                iy = hy & 0x7fffffff; /* |y| */

                if (((ix >= 0x7ff00000) && ((ix - 0x7ff00000) | unchecked((int)lx)) != 0) || /* x is nan */
                    ((iy >= 0x7ff00000) && ((iy - 0x7ff00000) | unchecked((int)ly)) != 0)) /* y is nan */
                    return x + y;
                if (x == y)
                    return x; /* x=y, return x */
                if ((ix | unchecked((int)lx)) == 0)
                { /* x == 0 */
                    x = FromHiLo(hy & unchecked((int)0x80000000u), 1u);
                    y = x * x;
                    if (y == x)
                        return y;
                    else
                        return x; /* raise underflow flag */
                }
                if (hx >= 0)
                { /* x > 0 */
                    if (hx > hy || ((hx == hy) && (lx > ly)))
                    { /* x > y, x -= ulp */
                        if (lx == 0)
                            hx -= 1;
                        lx -= 1;
                    }
                    else
                    { /* x < y, x += ulp */
                        lx += 1;
                        if (lx == 0)
                            hx += 1;
                    }
                }
                else
                { /* x < 0 */
                    if (hy >= 0 || hx > hy || ((hx == hy) && (lx > ly)))
                    { /* x < y, x -= ulp */
                        if (lx == 0)
                            hx -= 1;
                        lx -= 1;
                    }
                    else
                    { /* x > y, x += ulp */
                        lx += 1;
                        if (lx == 0)
                            hx += 1;
                    }
                }
                hy = hx & 0x7ff00000;
                if (hy >= 0x7ff00000)
                    return x + x; /* overflow */
                if (hy < 0x00100000)
                { /* underflow */
                    y = x * x;
                    if (y != x)
                    { /* raise underflow flag */
                        return FromHiLo(hx, lx);
                    }
                }
                return FromHiLo(hx, lx);
            }
        }

        // ------------------------------------------------------------------
        // ufbx_ceil, ufbx_math.c:1948-2020
        // ------------------------------------------------------------------

        public static double Ceil(double x)
        {
            const double huge = 1.0e300;

            unchecked
            {
                int i0, i1, j0;
                uint i, j;
                ulong bx = ToBits(x);
                i0 = unchecked((int)(uint)(bx >> 32));
                i1 = unchecked((int)(uint)bx);
                j0 = ((i0 >> 20) & 0x7ff) - 0x3ff;
                if (j0 < 20)
                {
                    if (j0 < 0)
                    { /* raise inexact if x != 0 */
                        if (huge + x > 0.0)
                        { /* return 0*sign(x) if |x|<1 */
                            if (i0 < 0)
                            {
                                i0 = unchecked((int)0x80000000u);
                                i1 = 0;
                            }
                            else if ((i0 | i1) != 0)
                            {
                                i0 = unchecked((int)0x3ff00000u);
                                i1 = 0;
                            }
                        }
                    }
                    else
                    {
                        i = 0x000fffffu >> j0;
                        if (((i0 & unchecked((int)i)) | i1) == 0)
                            return x; /* x is integral */
                        if (huge + x > 0.0)
                        { /* raise inexact flag */
                            if (i0 > 0)
                                i0 += 0x00100000 >> j0;
                            i0 &= unchecked((int)~i);
                            i1 = 0;
                        }
                    }
                }
                else if (j0 > 51)
                {
                    if (j0 == 0x400)
                        return x + x; /* inf or NaN */
                    else
                        return x; /* x is integral */
                }
                else
                {
                    i = 0xffffffffu >> (j0 - 20);
                    if ((i1 & unchecked((int)i)) == 0)
                        return x; /* x is integral */
                    if (huge + x > 0.0)
                    { /* raise inexact flag */
                        if (i0 > 0)
                        {
                            if (j0 == 20)
                                i0 += 1;
                            else
                            {
                                j = (uint)i1 + (1u << (52 - j0));
                                if (j < (uint)i1)
                                    i0 += 1; /* got a carry */
                                i1 = unchecked((int)j);
                            }
                        }
                        i1 &= unchecked((int)~i);
                    }
                }
                return FromHiLo(i0, (uint)i1);
            }
        }

        // ------------------------------------------------------------------
        // ufbx_rint, ufbx_math.c:2022-2074 (round-to-nearest-even; relies on
        // the default IEEE rounding mode, as the C implementation does)
        // ------------------------------------------------------------------

        private static readonly double[] Two52 =
        {
            4.50359962737049600000e+15,  /* 0x43300000, 0x00000000 */
            -4.50359962737049600000e+15, /* 0xC3300000, 0x00000000 */
        };

        public static double Rint(double x)
        {
            unchecked
            {
                int i0, j0, sx;
                uint i, i1;
                double w, t;
                ulong bt;
                ulong bx = ToBits(x);
                i0 = unchecked((int)(uint)(bx >> 32));
                i1 = (uint)bx;
                sx = (i0 >> 31) & 1;
                j0 = ((i0 >> 20) & 0x7ff) - 0x3ff;
                if (j0 < 20)
                {
                    if (j0 < 0)
                    {
                        if (((i0 & 0x7fffffff) | unchecked((int)i1)) == 0) return x;
                        i1 |= (uint)(i0 & 0x0fffff);
                        i0 &= unchecked((int)0xfffe0000u);
                        i0 |= unchecked((int)((i1 | (uint)(-(int)i1)) >> 12)) & 0x80000;
                        x = SetHi(x, i0);
                        w = Two52[sx] + x;
                        t = w - Two52[sx];
                        bt = ToBits(t);
                        i0 = unchecked((int)(uint)(bt >> 32));
                        t = FromHiLo((i0 & 0x7fffffff) | (sx << 31), (uint)bt);
                        return t;
                    }
                    else
                    {
                        i = 0x000fffffu >> j0;
                        if (((i0 & unchecked((int)i)) | unchecked((int)i1)) == 0) return x; /* x is integral */
                        i >>= 1;
                        if (((i0 & unchecked((int)i)) | unchecked((int)i1)) != 0)
                        {
                            if (j0 == 19) i1 = 0x40000000;
                            else i0 = (i0 & unchecked((int)~i)) | (0x20000 >> j0);
                        }
                    }
                }
                else if (j0 > 51)
                {
                    if (j0 == 0x400) return x + x; /* inf or NaN */
                    else return x; /* x is integral */
                }
                else
                {
                    i = 0xffffffffu >> (j0 - 20);
                    if ((i1 & i) == 0) return x; /* x is integral */
                    i >>= 1;
                    if ((i1 & i) != 0) i1 = (i1 & ~i) | (0x40000000u >> (j0 - 20));
                }
                x = FromHiLo(i0, i1);
                w = Two52[sx] + x;
                return w - Two52[sx];
            }
        }

        // ------------------------------------------------------------------
        // ufbx_isnan, ufbx_math.c:2076-2085
        // ------------------------------------------------------------------

        private static int IsNanInt(double x)
        {
            unchecked
            {
                int hx;
                uint lx;
                ulong bx = ToBits(x);
                hx = unchecked((int)(uint)(bx >> 32)) & 0x7fffffff;
                lx = (uint)bx;
                hx |= unchecked((int)((lx | (0u - lx)) >> 31));
                hx = 0x7ff00000 - hx;
                return (int)((uint)hx >> 31);
            }
        }

        public static bool IsNan(double x)
        {
            return IsNanInt(x) != 0;
        }
    }
}
