using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Ufbx.NET;

namespace Check
{
    // Bit-exact verification of UfbxMath against tools/math_vectors.txt
    // (72000 golden vectors generated by tools/mathvec.exe from the C build).
    //
    // File format (3 columns on every line):
    //   <fn> <argbits-hex16> <resultbits-hex16>
    //
    // For the two-argument functions (nextafter, fmin, fmax, copysign, atan2,
    // pow) the generator prints `xb | yb` -- the bitwise OR of both argument
    // bit patterns -- as the "arg" column (see tools/mathvec_impl.c), so the
    // second input is recovered per block from the fmin/fmax result columns:
    // fmax(x,y) and fmin(x,y) return one of their operands bit-exactly, hence
    //   y = fmax_res if fmax_res != x, else fmin_res if fmin_res != x, else x.
    // The recovered y is validated by checking (xb | yb) == the stored OR
    // column. Rows are grouped into blocks of 18 in generator order, flushed
    // at each "pow" row. atan2 is called as Atan2(x, y) matching the
    // generator's ufbx_atan2(x, y); `isnan` rows compare the integer 0/1,
    // not double bits.
    public static class Program
    {
        private struct VecLine
        {
            public string Fn;
            public ulong A;
            public ulong Res;
            public int No;
        }

        private static readonly string[] BlockFns =
        {
            "sqrt", "abs", "rint", "floor", "ceil", "isnan",
            "nextafter", "fmin", "fmax", "copysign",
            "sin", "cos", "tan", "asin", "acos", "atan",
            "atan2", "pow",
        };

        private static bool IsTwoArg(string fn)
        {
            return fn == "nextafter" || fn == "fmin" || fn == "fmax" ||
                   fn == "copysign" || fn == "atan2" || fn == "pow";
        }

        private static double DoubleFromBits(ulong bits)
        {
            return BitConverter.Int64BitsToDouble(unchecked((long)bits));
        }

        public static int Main(string[] args)
        {
            string path = args.Length > 1 ? args[1] : "tools/math_vectors.txt";
            string[] raw;
            try
            {
                raw = File.ReadAllLines(path);
            }
            catch (Exception e)
            {
                Console.WriteLine("ERROR: cannot read '{0}': {1}", path, e.Message);
                return 1;
            }

            long total = 0, passed = 0, failed = 0;
            int structErrors = 0, orMismatchBlocks = 0;
            int shown = 0;
            const int MaxShow = 20;

            var block = new List<VecLine>(18);
            var failCountByFn = new SortedDictionary<string, int>();

            void ShowMismatch(VecLine ln, ulong xB, ulong yB, ulong actual)
            {
                if (shown < MaxShow)
                {
                    Console.WriteLine(
                        "MISMATCH line {0}: {1} x={2:X16} y={3:X16} expected={4:X16} actual={5:X16}",
                        ln.No, ln.Fn, xB, yB, ln.Res, actual);
                }
                shown++;
                int c;
                failCountByFn.TryGetValue(ln.Fn, out c);
                failCountByFn[ln.Fn] = c + 1;
            }

            void Flush()
            {
                if (block.Count == 0)
                    return;

                if (block.Count != BlockFns.Length)
                {
                    Console.WriteLine("ERROR: incomplete block starting at line {0} ({1} lines, expected {2})",
                        block[0].No, block.Count, BlockFns.Length);
                    structErrors++;
                }

                for (int idx = 0; idx < block.Count && idx < BlockFns.Length; idx++)
                {
                    if (block[idx].Fn != BlockFns[idx])
                    {
                        Console.WriteLine("ERROR: line {0}: expected '{1}' but got '{2}'",
                            block[idx].No, BlockFns[idx], block[idx].Fn);
                        structErrors++;
                    }
                }

                ulong xB = 0;
                bool haveX = false;
                ulong fminRes = 0, fmaxRes = 0, orBits = 0;
                bool haveFmin = false, haveFmax = false, haveOr = false;

                foreach (VecLine t in block)
                {
                    if (!IsTwoArg(t.Fn))
                    {
                        if (!haveX)
                        {
                            xB = t.A;
                            haveX = true;
                        }
                        else if (t.A != xB)
                        {
                            if (shown < MaxShow)
                                Console.WriteLine("ERROR: line {0}: single-arg input {1:X16} != block input {2:X16}",
                                    t.No, t.A, xB);
                            shown++;
                            structErrors++;
                        }
                    }
                    else
                    {
                        if (!haveOr)
                        {
                            orBits = t.A;
                            haveOr = true;
                        }
                        else if (t.A != orBits)
                        {
                            if (shown < MaxShow)
                                Console.WriteLine("ERROR: line {0}: two-arg OR column {1:X16} != {2:X16}",
                                    t.No, t.A, orBits);
                            shown++;
                            structErrors++;
                        }
                        if (t.Fn == "fmin")
                        {
                            fminRes = t.Res;
                            haveFmin = true;
                        }
                        else if (t.Fn == "fmax")
                        {
                            fmaxRes = t.Res;
                            haveFmax = true;
                        }
                    }
                }

                if (!haveX || !haveOr || !haveFmin || !haveFmax)
                {
                    Console.WriteLine("ERROR: block starting at line {0} is missing required rows (x={1} or={2} fmin={3} fmax={4})",
                        block.Count > 0 ? block[0].No : 0, haveX, haveOr, haveFmin, haveFmax);
                    structErrors++;
                    block.Clear();
                    return;
                }

                // Recover y (second argument) from the fmin/fmax result rows.
                // fmin(x,y)/fmax(x,y) always return one of the operands
                // bit-exactly (including NaN operands), so:
                //   y > x  -> fmax returns y
                //   y < x  -> fmin returns y
                //   y == x -> both return x
                //   NaN operands -> the branch result still carries y's bits.
                ulong yB;
                if (fmaxRes != xB)
                    yB = fmaxRes;
                else if (fminRes != xB)
                    yB = fminRes;
                else
                    yB = xB;

                double x = DoubleFromBits(xB);
                double y = DoubleFromBits(yB);

                if ((xB | yB) != orBits)
                {
                    orMismatchBlocks++;
                    if (shown < MaxShow)
                        Console.WriteLine("OR-MISMATCH near line {0}: x={1:X16} y={2:X16} (x|y)={3:X16} expected={4:X16}",
                            block[0].No, xB, yB, xB | yB, orBits);
                    shown++;
                }

                foreach (VecLine t in block)
                {
                    total++;
                    ulong actual;
                    if (Eval(t.Fn, x, y, t.Res, out actual))
                    {
                        passed++;
                    }
                    else
                    {
                        failed++;
                        ShowMismatch(t, xB, yB, actual);
                    }
                }

                block.Clear();
            }

            for (int li = 0; li < raw.Length; li++)
            {
                string trimmed = raw[li].Trim();
                if (trimmed.Length == 0)
                    continue;

                string[] parts = trimmed.Split((char[])null, StringSplitOptions.RemoveEmptyEntries);
                if (parts.Length != 3)
                {
                    Console.WriteLine("ERROR: line {0}: expected 3 columns, got {1}: '{2}'", li + 1, parts.Length, trimmed);
                    structErrors++;
                    continue;
                }

                VecLine ln;
                ln.Fn = parts[0];
                ln.No = li + 1;
                if (!ulong.TryParse(parts[1], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ln.A) ||
                    !ulong.TryParse(parts[2], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ln.Res))
                {
                    Console.WriteLine("ERROR: line {0}: bad hex bits '{1}' / '{2}'", li + 1, parts[1], parts[2]);
                    structErrors++;
                    continue;
                }

                block.Add(ln);
                if (ln.Fn == "pow") // last row of each generator block
                    Flush();
            }
            Flush();

            Console.WriteLine();
            Console.WriteLine("mathvec: {0} vectors, {1} passed, {2} failed, {3} OR-column mismatches, {4} structural errors",
                total, passed, failed, orMismatchBlocks, structErrors);
            if (failCountByFn.Count > 0)
            {
                var sb = new StringBuilder("failures by fn:");
                foreach (var kv in failCountByFn)
                    sb.Append(' ').Append(kv.Key).Append('=').Append(kv.Value);
                Console.WriteLine(sb.ToString());
            }

            return (failed == 0 && structErrors == 0 && orMismatchBlocks == 0 && total == 72000) ? 0 : 1;
        }

        private static bool Eval(string fn, double x, double y, ulong expected, out ulong actual)
        {
            double r;
            switch (fn)
            {
                case "sqrt": r = UfbxMath.Sqrt(x); break;
                case "abs": r = UfbxMath.Abs(x); break;
                case "rint": r = UfbxMath.Rint(x); break;
                case "floor": r = UfbxMath.Floor(x); break;
                case "ceil": r = UfbxMath.Ceil(x); break;
                case "isnan":
                    actual = UfbxMath.IsNan(x) ? 1UL : 0UL;
                    return actual == expected;
                case "nextafter": r = UfbxMath.NextAfter(x, y); break;
                case "fmin": r = UfbxMath.FMin(x, y); break;
                case "fmax": r = UfbxMath.FMax(x, y); break;
                case "copysign": r = UfbxMath.CopySign(x, y); break;
                case "sin": r = UfbxMath.Sin(x); break;
                case "cos": r = UfbxMath.Cos(x); break;
                case "tan": r = UfbxMath.Tan(x); break;
                case "asin": r = UfbxMath.Asin(x); break;
                case "acos": r = UfbxMath.Acos(x); break;
                case "atan": r = UfbxMath.Atan(x); break;
                case "atan2": r = UfbxMath.Atan2(x, y); break; /* generator: ufbx_atan2(x, y) */
                case "pow": r = UfbxMath.Pow(x, y); break;
                default:
                    Console.WriteLine("ERROR: unknown fn '{0}'", fn);
                    actual = 0;
                    return false;
            }
            actual = unchecked((ulong)BitConverter.DoubleToInt64Bits(r));
            return actual == expected;
        }
    }
}
