// CLI commands `hash` and `goldens` for the golden-hash verification
// (tools/golden_hashes.txt, generated by C `test/hash_scene.exe`).
//
//   Ufbx.NET.Tests hash <path-to-file> [frame]
//       prints one line `<hash16> <frame> <path>` in the golden file format.
//
//   Ufbx.NET.Tests goldens <golden-file> [--data-dir <dir>] [--filter <substr>] [--max N]
//       hashes each referenced file and prints a summary line
//       `goldens: N files, M matched, K mismatched, E load-errors`
//       plus the first 50 mismatch details. Exit: 0 all matched, 1 mismatches,
//       3 no mismatches but load errors (including the loader seam not being
//       implemented yet), 4 usage/IO error.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Ufbx.NET;

namespace Ufbx.NET.Tests
{
    public static class HashCommands
    {
        private const string DefaultDataDir = @"C:\Workspace\_analyze_ufbx";
        private const int MaxMismatchReport = 50;

        public static int Run(string[] args)
        {
            if (args.Length > 0 && args[0] == "hash") return RunHash(args);
            if (args.Length > 0 && args[0] == "goldens") return RunGoldens(args);
            return 4;
        }

        // `Ufbx.NET.Tests hash <path-to-file> [frame]`
        private static int RunHash(string[] args)
        {
            if (args.Length < 2)
            {
                Console.Error.WriteLine("Usage: Ufbx.NET.Tests hash <path-to-file> [frame]");
                return 4;
            }
            string path = args[1];
            int frame = 0;
            if (args.Length > 2 && !int.TryParse(args[2], out frame))
            {
                Console.Error.WriteLine($"Invalid frame: {args[2]}");
                return 4;
            }

            UfbxScene scene;
            try
            {
                scene = SceneProvider.Load(path, frame);
            }
            catch (Exception e)
            {
                Console.Error.WriteLine($"error: failed to load scene: {e.Message}");
                return 2;
            }

            ulong hash = UfbxHashScene.HashScene(scene);
            // Golden format: lowercase hex zero-padded to 16 digits.
            Console.WriteLine(hash.ToString("x16", CultureInfo.InvariantCulture) + " " +
                              frame.ToString(CultureInfo.InvariantCulture) + " " + path);
            return 0;
        }

        private sealed class GoldenEntry
        {
            public ulong Hash;
            public int Frame;
            public string Path;
        }

        // `Ufbx.NET.Tests goldens <golden-file> [--data-dir <dir>] [--filter <substr>] [--max N]`
        private static int RunGoldens(string[] args)
        {
            if (args.Length < 2)
            {
                Console.Error.WriteLine(
                    "Usage: Ufbx.NET.Tests goldens <golden-file> [--data-dir <dir>] [--filter <substr>] [--max N]");
                return 4;
            }
            string goldenFile = args[1];
            string dataDir = DefaultDataDir;
            string filter = null;
            int max = int.MaxValue;
            for (int i = 2; i < args.Length; i++)
            {
                if (args[i] == "--data-dir" && i + 1 < args.Length) dataDir = args[++i];
                else if (args[i] == "--filter" && i + 1 < args.Length) filter = args[++i];
                else if (args[i] == "--max" && i + 1 < args.Length &&
                         int.TryParse(args[++i], out int m)) max = m;
                else
                {
                    Console.Error.WriteLine($"Unknown flag: {args[i]}");
                    return 4;
                }
            }

            string[] lines;
            try
            {
                lines = File.ReadAllLines(goldenFile);
            }
            catch (Exception e)
            {
                Console.Error.WriteLine($"error: failed to read golden file: {e.Message}");
                return 4;
            }

            var entries = new List<GoldenEntry>();
            foreach (string raw in lines)
            {
                string line = raw.Trim();
                if (line.Length == 0) continue;
                // `<hash16> <frame> <path>` (gen_golden.sh excludes spaces in paths)
                string[] parts = line.Split(new[] { ' ' }, 3);
                if (parts.Length != 3) continue;
                if (!ulong.TryParse(parts[0], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ulong hash)) continue;
                if (!int.TryParse(parts[1], out int frame)) continue;
                if (filter != null && parts[2].IndexOf(filter, StringComparison.Ordinal) < 0) continue;
                entries.Add(new GoldenEntry { Hash = hash, Frame = frame, Path = parts[2] });
                if (entries.Count >= max) break;
            }

            int matched = 0, mismatched = 0, loadErrors = 0;
            var mismatches = new List<string>();
            foreach (GoldenEntry entry in entries)
            {
                string fullPath = Path.Combine(dataDir, entry.Path.Replace('/', Path.DirectorySeparatorChar));
                UfbxScene scene;
                try
                {
                    scene = SceneProvider.Load(fullPath, entry.Frame);
                }
                catch (Exception)
                {
                    loadErrors++;
                    continue;
                }

                ulong actual = UfbxHashScene.HashScene(scene);
                if (actual == entry.Hash)
                {
                    matched++;
                }
                else
                {
                    mismatched++;
                    if (mismatches.Count < MaxMismatchReport)
                    {
                        mismatches.Add($"{entry.Path}: expected {entry.Hash:x16} " +
                                       $"actual {actual:x16} frame {entry.Frame}");
                    }
                }
            }

            foreach (string m in mismatches) Console.WriteLine(m);
            Console.WriteLine($"goldens: {entries.Count} files, {matched} matched, " +
                              $"{mismatched} mismatched, {loadErrors} load-errors");

            if (mismatched > 0) return 1;
            if (loadErrors > 0) return 3; // nothing (or only part) could be verified
            return 0;
        }
    }
}
