<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Ufbx.NET.Tests</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Ufbx.NET\Ufbx.NET.csproj" />
  </ItemGroup>
</Project>
