// C reference oracle for the ported inflate / bit-stream / Huffman layer
// (src/Ufbx.NET/Parse/{BitStream,Huff,Inflate}.cs).
//
// It #includes ufbx.c as a single translation unit so every `static ufbxi_*` internal
// (ufbx_inflate, ufbxi_adler32, ufbxi_bit_stream_init, ufbxi_bit_refill, ...) is directly
// callable, exactly like the golden build.
//
//   zig cc -O2 -std=c11 -I C:/Workspace/_analyze_ufbx tools/inflate_oracle.c -o tools/inflate_oracle.exe
//   tools/inflate_oracle.exe tools/inflate_corpus.txt tools/inflate_oracle.txt
//
// The corpus is generated by the C# side (`dotnet run --project tools/InflateCheck -c Release
// -- inflatecorpus`) so both sides run *identical* inputs; this program only answers with what
// C produces. The C# harness (tools/InflateCheck) replays every record and diffs the answers.
//
// Corpus grammar (one record per line, whitespace separated, `hex` = lowercase hex):
//   S <sid> <hex>                                  define stream/blob <sid> with these bytes
//   A <sid> <off> <len>                            ufbxi_adler32(stream + off, len)
//   D <idx> <sid> <nh> <nc> <fast> <mode> <step> <bufsz> <dst> <hint> <cancel_at>
//                                                  ufbx_inflate() with the given input
//   B <idx> <sid> <data_size> <step> <bufsz> <hint> <cancel_at> <max_steps> <fields>
//                                                  raw ufbxi_bit_refill() driver trace;
//                                                  `<fields>` = "-" (1 bit per step) or a
//                                                  comma separated list of consumed bit widths
//   F <idx> <sid> <nh> <nc> <fast> <dst> <psid>    single-bit-flip fuzz over stream <sid>
//
// Answer grammar (written to the output file):
//   A <sid> <off> <len> <adler-hex8>
//   D <idx> <res> <dst-digest-hex16> <cb-count> <cb-monotone> <cb-total-ok> <cb-last> <cb-digest>
//   B <idx> <steps> <eof-step> <stop-error> <trace-digest> <cb-count> <cb-monotone> <cb-total-ok>
//       <cb-last> <cb-digest>
//   F <idx> <byte> <bit> <res> <dst-digest-hex16>
//   V <idx> <step> <bits> <left> <ptr> <end> <yield> <realend> <num-read> <input-left>
//       <buffer-size> <array-id> <stop-error>      only with `-v`, per-step B trace lines
//
// `mode` for D: 0 = whole memory (data == stream, data_size == total),
//               1 = read_fn only (data_size == 0),
//               2 = prefix of `step` bytes in `data` + read_fn continuing after them.
// `step` is the max bytes a single read_fn() call hands out (SIZE_MAX = "blocking" reader).
// `bufsz` > 256 installs `input->buffer` of that size, 0 = use the internal 256 byte buffer.
// `hint` is `progress_interval_hint` (0 means "use the default 0x4000"). `cancel_at`:
//   -2 = no progress callback at all, -1 = callback that always continues,
//    N >= 0 = callback that returns CANCEL on the (N+1)-th call.
//
// Digests are FNV-1a 64 over the raw bytes of `dst` (whole `dst_size` bytes, zero initialised)
// so partially written output is compared too, and over the ASCII text of the trace/progress
// lines (the C# side formats the same decimal text, see InflateCheck.cs `AppendTrace`).

#include "ufbx.c"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_STREAMS 4096
#define HEX_BUFSZ (1 << 23)

#define FNV_OFFSET UINT64_C(14695981039346656037)
#define FNV_PRIME UINT64_C(1099511628211)

static char *g_stream[MAX_STREAMS];
static size_t g_stream_len[MAX_STREAMS];

static uint64_t fnv_bytes(uint64_t h, const void *data, size_t n)
{
	const unsigned char *p = (const unsigned char*)data;
	for (size_t i = 0; i < n; i++) {
		h ^= (uint64_t)p[i];
		h *= FNV_PRIME;
	}
	return h;
}

// -- read_fn: a capped memory reader, the exact twin of the C# harness' ChunkReader

typedef struct {
	const char *data;
	size_t total;
	size_t pos;
	size_t step;
} mem_reader;

static size_t mem_reader_fn(void *user, void *dst, size_t size)
{
	mem_reader *r = (mem_reader*)user;
	size_t n = size < r->step ? size : r->step;
	size_t left = r->total - r->pos;
	if (n > left) n = left;
	if (n > 0) {
		memcpy(dst, r->data + r->pos, n);
		r->pos += n;
	}
	return n;
}

// -- progress_cb: records every call, optionally cancels

typedef struct {
	uint64_t digest;
	size_t count;
	bool monotone;
	bool total_ok;
	uint64_t last;
	uint64_t expect_total;
	long cancel_at;
} progress_rec;

static ufbx_progress_result progress_fn(void *user, const ufbx_progress *p)
{
	progress_rec *c = (progress_rec*)user;
	char buf[64];
	int n = snprintf(buf, sizeof(buf), "%llu %llu\n",
		(unsigned long long)p->bytes_read, (unsigned long long)p->bytes_total);
	c->digest = fnv_bytes(c->digest, buf, (size_t)n);
	c->count++;
	if (p->bytes_read < c->last) c->monotone = false;
	c->last = p->bytes_read;
	if (p->bytes_total != c->expect_total) c->total_ok = false;
	if (c->cancel_at >= 0 && (long)c->count > c->cancel_at) return UFBX_PROGRESS_CANCEL;
	return UFBX_PROGRESS_CONTINUE;
}

// -- tokenizer

static char *next_tok(char **pp)
{
	char *p = *pp;
	while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
	if (!*p) return NULL;
	char *start = p;
	while (*p && *p != ' ' && *p != '\t' && *p != '\r' && *p != '\n') p++;
	char save = *p;
	*p = 0;
	*pp = p + (save ? 1 : 0);
	return start;
}

static size_t hex_decode(const char *hex, char *out)
{
	size_t n = 0;
	for (const char *p = hex; p[0] && p[1]; p += 2) {
		int hi = (p[0] >= 'a') ? (p[0] - 'a' + 10) : (p[0] - '0');
		int lo = (p[1] >= 'a') ? (p[1] - 'a' + 10) : (p[1] - '0');
		out[n++] = (char)((hi << 4) | lo);
	}
	return n;
}

static void setup_input(ufbx_inflate_input *input, mem_reader *reader, long sid,
	long mode, size_t step, size_t bufsz, char **user_buf_out)
{
	memset(input, 0, sizeof(*input));
	memset(reader, 0, sizeof(*reader));
	input->total_size = g_stream_len[sid];
	*user_buf_out = NULL;
	if (bufsz > 0) {
		*user_buf_out = (char*)malloc(bufsz);
		memset(*user_buf_out, 0, bufsz);
		input->buffer = *user_buf_out;
		input->buffer_size = bufsz;
	}
	if (mode == 0) {
		input->data = g_stream[sid];
		input->data_size = g_stream_len[sid];
	} else {
		if (mode == 2) {
			input->data = g_stream[sid];
			input->data_size = step;
		}
		reader->data = g_stream[sid];
		reader->total = g_stream_len[sid];
		reader->pos = mode == 2 ? step : 0;
		reader->step = step;
		input->read_fn = mem_reader_fn;
		input->read_user = reader;
	}
}

static void setup_progress(ufbx_inflate_input *input, progress_rec *prog,
	uint64_t hint, long cancel_at)
{
	memset(prog, 0, sizeof(*prog));
	prog->digest = FNV_OFFSET;
	prog->monotone = true;
	prog->total_ok = true;
	prog->last = (uint64_t)0 - 1;
	prog->cancel_at = cancel_at;
	input->progress_interval_hint = hint;
	if (cancel_at >= -1) {
		prog->expect_total = input->total_size + input->progress_size_before + input->progress_size_after;
		input->progress_cb.fn = progress_fn;
		input->progress_cb.user = prog;
	}
}

// -- D: ufbx_inflate()

static void run_inflate_record(FILE *out, long idx, long sid, bool no_header, bool no_checksum,
	size_t fast_bits, long mode, size_t step, size_t bufsz, size_t dst_size,
	uint64_t hint, long cancel_at)
{
	ufbx_inflate_input input;
	mem_reader reader;
	progress_rec prog;
	char *user_buf = NULL;
	setup_input(&input, &reader, sid, mode, step, bufsz, &user_buf);
	setup_progress(&input, &prog, hint, cancel_at);
	input.no_header = no_header;
	input.no_checksum = no_checksum;
	input.internal_fast_bits = fast_bits;

	char *dst = (char*)calloc(dst_size > 0 ? dst_size : 1, 1);
	memset(dst, 0, dst_size > 0 ? dst_size : 1);
	ufbx_inflate_retain retain;
	memset(&retain, 0, sizeof(retain));

	ptrdiff_t res = ufbx_inflate(dst, dst_size, &input, &retain);

	uint64_t digest = fnv_bytes(FNV_OFFSET, dst, dst_size);
	fprintf(out, "D %ld %td %016llx %llu %d %d %llu %016llx\n",
		idx, res, (unsigned long long)digest,
		(unsigned long long)prog.count, prog.monotone ? 1 : 0, prog.total_ok ? 1 : 0,
		(unsigned long long)prog.last, (unsigned long long)prog.digest);

	free(dst);
	free(user_buf);
}

// -- B: raw bit-stream driver

static void run_driver_record(FILE *out, long idx, long sid, size_t data_size, size_t step,
	size_t bufsz, uint64_t hint, long cancel_at, long max_steps,
	const long *fields, long num_fields, bool verbose)
{
	ufbx_inflate_input input;
	mem_reader reader;
	progress_rec prog;
	char *user_buf = NULL;

	memset(&input, 0, sizeof(input));
	memset(&reader, 0, sizeof(reader));
	input.total_size = g_stream_len[sid];
	if (bufsz > 0) {
		user_buf = (char*)malloc(bufsz);
		memset(user_buf, 0, bufsz);
		input.buffer = user_buf;
		input.buffer_size = bufsz;
	}
	if (data_size > 0) {
		input.data = g_stream[sid];
		input.data_size = data_size;
	}
	if (step > 0 && data_size < g_stream_len[sid]) {
		reader.data = g_stream[sid];
		reader.total = g_stream_len[sid];
		reader.pos = data_size;
		reader.step = step;
		input.read_fn = mem_reader_fn;
		input.read_user = &reader;
	}
	setup_progress(&input, &prog, hint, cancel_at);

	ufbxi_bit_stream s;
	memset(&s, 0, sizeof(s));
	ufbxi_bit_stream_init(&s, &input);

	uint64_t bits = s.bits;
	size_t left = s.left;
	const char *data = s.chunk_ptr;
	uint64_t trace = FNV_OFFSET;
	long eof_step = -1;
	long steps = 0;
	char tbuf[256];

	for (long i = 0; i < max_steps; i++) {
		ufbxi_bit_refill(&bits, &left, &data, &s);

		long array_id = 3;
		if (input.data && s.chunk_begin == (const char*)input.data) array_id = 0;
		else if (s.chunk_begin == (const char*)s.local_buffer) array_id = 1;
		else if (input.buffer && s.chunk_begin == (const char*)input.buffer) array_id = 2;

		int n = snprintf(tbuf, sizeof(tbuf), "%ld %llu %llu %llu %llu %llu %llu %llu %llu %llu %d %d\n",
			i,
			(unsigned long long)bits,
			(unsigned long long)left,
			(unsigned long long)(ptrdiff_t)(data - s.chunk_begin),
			(unsigned long long)(ptrdiff_t)(s.chunk_end - s.chunk_begin),
			(unsigned long long)(ptrdiff_t)(s.chunk_yield - s.chunk_begin),
			(unsigned long long)(ptrdiff_t)(s.chunk_real_end - s.chunk_begin),
			(unsigned long long)s.num_read_before_chunk,
			(unsigned long long)s.input_left,
			(unsigned long long)s.buffer_size,
			(int)array_id,
			(int)s.stop_error);
		trace = fnv_bytes(trace, tbuf, (size_t)n);
		if (verbose) fprintf(out, "V %ld %s", idx, tbuf);
		steps++;

		if (s.stop_error != 0) {
			eof_step = i;
			break;
		}
		size_t consume = 1;
		if (num_fields > 0) {
			consume = (size_t)fields[i % num_fields];
		}
		bits >>= consume;
		left -= consume;
	}

	fprintf(out, "B %ld %ld %ld %d %016llx %llu %d %d %llu %016llx\n",
		idx, steps, eof_step, (int)s.stop_error, (unsigned long long)trace,
		(unsigned long long)prog.count, prog.monotone ? 1 : 0, prog.total_ok ? 1 : 0,
		(unsigned long long)prog.last, (unsigned long long)prog.digest);

	free(user_buf);
}

// -- F: single-bit-flip fuzz

static void run_inflate_flip(FILE *out, long idx, size_t byte_ix, int bit, char *data, size_t n,
	bool no_header, bool no_checksum, size_t fast_bits, size_t dst_size)
{
	ufbx_inflate_input input;
	memset(&input, 0, sizeof(input));
	input.total_size = n;
	input.data = data;
	input.data_size = n;
	input.no_header = no_header;
	input.no_checksum = no_checksum;
	input.internal_fast_bits = fast_bits;

	char *dst = (char*)calloc(dst_size > 0 ? dst_size : 1, 1);
	ufbx_inflate_retain retain;
	memset(&retain, 0, sizeof(retain));
	ptrdiff_t res = ufbx_inflate(dst, dst_size, &input, &retain);
	uint64_t digest = fnv_bytes(FNV_OFFSET, dst, dst_size);
	fprintf(out, "F %ld %llu %d %td %016llx\n", idx, (unsigned long long)byte_ix, bit, res,
		(unsigned long long)digest);
	free(dst);
}

static void run_fuzz_record(FILE *out, long idx, long sid, bool no_header, bool no_checksum,
	size_t fast_bits, size_t dst_size)
{
	size_t n = g_stream_len[sid];
	char *copy = (char*)malloc(n > 0 ? n : 1);
	for (size_t byte_ix = 0; byte_ix < n; byte_ix++) {
		for (int bit = 0; bit < 8; bit++) {
			memcpy(copy, g_stream[sid], n);
			copy[byte_ix] ^= (char)(1u << (unsigned)bit);
			run_inflate_flip(out, idx, byte_ix, bit, copy, n, no_header, no_checksum, fast_bits, dst_size);
		}
	}
	free(copy);
}

int main(int argc, char **argv)
{
	const char *in_path = argc > 1 ? argv[1] : "tools/inflate_corpus.txt";
	const char *out_path = argc > 2 ? argv[2] : "tools/inflate_oracle.txt";
	bool verbose = false;
	for (int i = 1; i < argc; i++) if (!strcmp(argv[i], "-v")) verbose = true;

	FILE *in = fopen(in_path, "rb");
	if (!in) { fprintf(stderr, "inflate_oracle: cannot open %s\n", in_path); return 1; }
	FILE *out = fopen(out_path, "wb");
	if (!out) { fprintf(stderr, "inflate_oracle: cannot open %s\n", out_path); return 1; }

	static char line[HEX_BUFSZ];
	long lineno = 0;
	while (fgets(line, sizeof(line), in)) {
		lineno++;
		char *p = line;
		char *tok = next_tok(&p);
		if (!tok) continue;
		if (tok[0] == '#') continue;

		if (tok[0] == 'S') {
			long sid = atol(next_tok(&p));
			char *hex = next_tok(&p);
			char *buf;
			size_t n;
			if (!hex || strcmp(hex, "-") == 0) {
				// `-` spells an empty stream: a whitespace-separated grammar cannot carry an
				// empty token.
				buf = (char*)malloc(1);
				buf[0] = 0;
				n = 0;
			} else {
				n = strlen(hex) / 2;
				buf = (char*)malloc(n > 0 ? n : 1);
				n = hex_decode(hex, buf);
			}
			if (sid < 0 || sid >= MAX_STREAMS) { fprintf(stderr, "bad sid %ld\n", sid); return 1; }
			g_stream[sid] = buf;
			g_stream_len[sid] = n;
		} else if (tok[0] == 'A') {
			long sid = atol(next_tok(&p));
			size_t off = (size_t)strtoull(next_tok(&p), NULL, 10);
			size_t len = (size_t)strtoull(next_tok(&p), NULL, 10);
			uint32_t a = ufbxi_adler32(g_stream[sid] + off, len);
			fprintf(out, "A %ld %llu %llu %08x\n", sid, (unsigned long long)off,
				(unsigned long long)len, a);
		} else if (tok[0] == 'D') {
			long idx = atol(next_tok(&p));
			long sid = atol(next_tok(&p));
			bool nh = atol(next_tok(&p)) != 0;
			bool nc = atol(next_tok(&p)) != 0;
			size_t fast = (size_t)atol(next_tok(&p));
			long mode = atol(next_tok(&p));
			size_t step = (size_t)strtoull(next_tok(&p), NULL, 10);
			size_t bufsz = (size_t)strtoull(next_tok(&p), NULL, 10);
			size_t dst = (size_t)strtoull(next_tok(&p), NULL, 10);
			uint64_t hint = strtoull(next_tok(&p), NULL, 10);
			long cancel_at = atol(next_tok(&p));
			run_inflate_record(out, idx, sid, nh, nc, fast, mode, step, bufsz, dst, hint, cancel_at);
		} else if (tok[0] == 'B') {
			long idx = atol(next_tok(&p));
			long sid = atol(next_tok(&p));
			size_t data_size = (size_t)strtoull(next_tok(&p), NULL, 10);
			size_t step = (size_t)strtoull(next_tok(&p), NULL, 10);
			size_t bufsz = (size_t)strtoull(next_tok(&p), NULL, 10);
			uint64_t hint = strtoull(next_tok(&p), NULL, 10);
			long cancel_at = atol(next_tok(&p));
			long max_steps = atol(next_tok(&p));
			char *ftok = next_tok(&p);
			long fields[64];
			long num_fields = 0;
			if (ftok && strcmp(ftok, "-") != 0) {
				char *q = ftok;
				while (q && num_fields < 64) {
					fields[num_fields++] = strtol(q, &q, 10);
					if (*q == ',') q++;
				}
			}
			run_driver_record(out, idx, sid, data_size, step, bufsz, hint, cancel_at, max_steps,
				fields, num_fields, verbose);
		} else if (tok[0] == 'F') {
			long idx = atol(next_tok(&p));
			long sid = atol(next_tok(&p));
			bool nh = atol(next_tok(&p)) != 0;
			bool nc = atol(next_tok(&p)) != 0;
			size_t fast = (size_t)atol(next_tok(&p));
			size_t dst = (size_t)strtoull(next_tok(&p), NULL, 10);
			next_tok(&p); // payload stream id: the C# side re-derives the expected digest
			run_fuzz_record(out, idx, sid, nh, nc, fast, dst);
		} else {
			fprintf(stderr, "inflate_oracle: unknown record on line %ld\n", lineno);
			return 1;
		}
	}

	fclose(in);
	fclose(out);
	return 0;
}
